### ISSUE TITLE
Picked up Red Herring in Goblin Minigame

### ISSUE THREAD

**Issue by ccoop95** [MelvorIdle/melvoridle.github.io#1082]
No attacks were registering after, could not close the minigame, had to Force Save and task manager kill the process

Save corrupted after trying to load back in. Fix my Save not working

TypeError: Cannot read property '1' of undefined
    at updatePlayerBaseStats (https://melvoridle.com/assets/js/game/combat.js?942:296:304)
    at updatePlayerStats (https://melvoridle.com/assets/js/game/combat.js?942:288:216)
    at updateWindow (https://melvoridle.com/assets/js/game/main.js?942:16:471)
    at finaliseLoad (https://melvoridle.com/assets/js/game/main.js?942:329:36)
    at selectCharacter (https://melvoridle.com/assets/js/game/main.js?942:318:254)
    at onloadEvent (https://melvoridle.com/assets/js/game/save.js?942:74:286)
    at HTMLDivElement.<anonymous> (https://melvoridle.com/assets/js/game/save.js?942:77:454)
    at HTMLDivElement.<anonymous> (https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6:84821)
    at Function.each (https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6:2967)
    at C.fn.init.each (https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6:1453)

**Comment by MelvorIdle** [comment]
Fixed in Alpha v0.21
