### ISSUE TITLE
Cloud Save: Game failed to load.

### ISSUE THREAD

**Issue by MrDraXuz** [MelvorIdle/melvoridle.github.io#1186]
**Describe the bug**
Failed to load my cloud save, assuming it wasn't able to find my save on the server. It tried fixing the local save which just deleted the data and gave me an almost fresh character. Unfortunately it did the same thing when I tried it on the steam client.

**To Reproduce**
Simply try loading a cloud save from January.

**Expected behavior**
Android and steam v0.21 Expected to be able to log in and play on my cloud save.

**Screenshots**
First is my cloud save, second is the local save that has over written my old save.
![Screenshot_20210813-124226_Melvor Idle](https://user-images.githubusercontent.com/88899182/129392705-b5bfbd22-e773-4e00-8255-011189cbeb75.jpg)
![Screenshot_20210813-124236_Melvor Idle](https://user-images.githubusercontent.com/88899182/129392739-42693352-5f5f-4360-880a-6e72c2c22468.jpg)

**Browser**
Andriod and steam v.021

**Console output**
TypeError: Cannot read property 'get' of undefined
    at addPurchase (https://android.melvoridle.com/adfree/assets/js/game/serializeSave.js?1012:131:99)
    at cleanSaveGame (https://android.melvoridle.com/adfree/assets/js/game/serializeSave.js?1012:134:1)
    at setGlobalsFromSaveGame (https://android.melvoridle.com/adfree/assets/js/game/save.js?1012:45:171)
    at loadData (https://android.melvoridle.com/adfree/assets/js/game/save.js?1012:14:99)
    at finaliseLoad (https://android.melvoridle.com/adfree/assets/js/game/main.js?1012:326:80)
    at selectCharacter (https://android.melvoridle.com/adfree/assets/js/game/main.js?1012:318:290)
    at onloadEvent (https://android.melvoridle.com/adfree/assets/js/game/save.js?1012:60:262)
    at HTMLDivElement.<anonymous> (https://android.melvoridle.com/adfree/assets/js/game/save.js?1012:63:230)
    at HTMLDivElement.<anonymous> (https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6:84821)
    at Function.each (https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6:2967)

**Are you using any scripts?**
No.

**Comment by MelvorIdle** [comment]
This has now been hotfixed
