### ISSUE TITLE
Cloud save file error - Chrome & iOS

### ISSUE THREAD

**Issue by xClow** [MelvorIdle/melvoridle.github.io#1192]
**Describe the bug**
It's been a while since I last played the game and want to come try all the new updates. When trying to load my cloud save from Nov 20, 2020 on iOS or Chrome it gives me an error, tried clicking fix save but that doesn't work.

**To Reproduce**
1. Go to "Cloud Saves" for cloud account - "clow" xclowz@gmail.com
2. Click on Save file #1 "rhet_capiletti"
3. See error

**Expected behavior**
Being able to log in.

**Browser**
Google Chrome Version 92.0.4515.131 (Official Build) (64-bit)
iOS version 14.6

**Console output**
TypeError: Cannot read property 'get' of undefined
    at addPurchase (https://melvoridle.com/assets/js/game/serializeSave.js?1012:131:99)
    at cleanSaveGame (https://melvoridle.com/assets/js/game/serializeSave.js?1012:134:1)
    at setGlobalsFromSaveGame (https://melvoridle.com/assets/js/game/save.js?1012:45:171)
    at loadData (https://melvoridle.com/assets/js/game/save.js?1012:14:99)
    at finaliseLoad (https://melvoridle.com/assets/js/game/main.js?1012:326:80)
    at selectCharacter (https://melvoridle.com/assets/js/game/main.js?1012:318:290)
    at onloadEvent (https://melvoridle.com/assets/js/game/save.js?1012:60:262)
    at HTMLDivElement.<anonymous> (https://melvoridle.com/assets/js/game/save.js?1012:63:230)
    at HTMLDivElement.<anonymous> (https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6:84821)
    at Function.each (https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6:2967)

**Are you using any scripts?**
No scripts enabled.

**Comment by coolrox95** [comment]
Issue was fixed in an update.
