### ISSUE TITLE
Can't get on save

### ISSUE THREAD

**Issue by JefKanon** [MelvorIdle/melvoridle.github.io#1221]
TypeError: Cannot read property 'get' of undefined
    at addPurchase (https://android.melvoridle.com/assets/js/game/serializeSave.js?1038:133:99)
    at cleanSaveGame (https://android.melvoridle.com/assets/js/game/serializeSave.js?1038:136:1)
    at setGlobalsFromSaveGame (https://android.melvoridle.com/assets/js/game/save.js?1038:45:171)
    at loadData (https://android.melvoridle.com/assets/js/game/save.js?1038:14:99)
    at finaliseLoad (https://android.melvoridle.com/assets/js/game/main.js?1038:325:80)
    at selectCharacter (https://android.melvoridle.com/assets/js/game/main.js?1038:317:290)
    at onloadEvent (https://android.melvoridle.com/assets/js/game/save.js?1038:60:267)
    at HTMLDivElement.<anonymous> (https://android.melvoridle.com/assets/js/game/save.js?1038:64:251)
    at HTMLDivElement.<anonymous> (https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6:84821)
    at Function.each (https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6:2967)

**Comment by abduct3d** [comment]
Same Issue here
