### ISSUE TITLE
Cloud character loading 

### ISSUE THREAD

**Issue by snowpin** [MelvorIdle/melvoridle.github.io#1284]
I get an error every time I  try and load my character on both iOS ans android this is the error on Android.

'TypeError: Cannot read property 'get' of undefined
    at addPurchase (https://android.melvoridle.com/assets/js/game/serializeSave.js?1109:133:99)
    at cleanSaveGame (https://android.melvoridle.com/assets/js/game/serializeSave.js?1109:136:1)
    at setGlobalsFromSaveGame (https://android.melvoridle.com/assets/js/game/save.js?1109:45:171)
    at loadData (https://android.melvoridle.com/assets/js/game/save.js?1109:14:99)
    at finaliseLoad (https://android.melvoridle.com/assets/js/game/main.js?1109:325:80)
    at selectCharacter (https://android.melvoridle.com/assets/js/game/main.js?1109:317:290)
    at onloadEvent (https://android.melvoridle.com/assets/js/game/save.js?1109:60:267)
    at HTMLDivElement.<anonymous> (https://android.melvoridle.com/assets/js/game/save.js?1109:64:251)
    at HTMLDivElement.<anonymous> (https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6:84821)
    at Function.each (https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6:2967)'

**Comment by snowpin** [comment]
Seems to have fixed itself after a week.
