### ISSUE TITLE
Issue with local saves

### ISSUE THREAD

**Issue by austin-wiechman** [MelvorIdle/melvoridle.github.io#1330]
**Describe the bug**
Whenever I exit and reopen/reload the game, the local save is missing. The cloud save is available, so I can continue playing. But the local save seems unable to persist. If I use the 'Fix my save' button, it seems to persist for ~1 reload. But then the issue comes back. Saving and reuploading the save seems to have a similar effect. The issue began sometime in the past several days.

**To Reproduce**
1. Go to a game save
2. Click on 'Close Tab'
3. Reopen 'Melvor Idle'

**Expected behavior**
The local save would stay.

**Screenshots**

**Browser**
Brave: v1.29.77

**Console output (Obtained after loading cloud save)**
```
62Unchecked runtime.lastError: The message port closed before a response was received.
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/sm/57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/popper.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
prebid.min.js:1 fun-hooks: referenced 'registerAdserver' but it was never created
(anonymous) @ prebid.min.js:1
(anonymous) @ prebid.min.js:1
ready.u.ready @ prebid.min.js:1
S.processQueue @ prebid.min.js:1
(anonymous) @ prebid.min.js:1
(anonymous) @ prebid.min.js:1
(anonymous) @ prebid.min.js:1
prebid.min.js:1 fun-hooks: referenced 'adpod' but it was never created
(anonymous) @ prebid.min.js:1
(anonymous) @ prebid.min.js:1
ready.u.ready @ prebid.min.js:1
S.processQueue @ prebid.min.js:1
(anonymous) @ prebid.min.js:1
(anonymous) @ prebid.min.js:1
(anonymous) @ prebid.min.js:1
prebid.min.js:1 fun-hooks: referenced 'realTimeData' but it was never created
(anonymous) @ prebid.min.js:1
(anonymous) @ prebid.min.js:1
ready.u.ready @ prebid.min.js:1
S.processQueue @ prebid.min.js:1
(anonymous) @ prebid.min.js:1
(anonymous) @ prebid.min.js:1
(anonymous) @ prebid.min.js:1
Error with Permissions-Policy header: Unrecognized feature: 'interest-cohort'.
Error with Permissions-Policy header: Unrecognized feature: 'interest-cohort'.
cloud.js?1120:76 Connected to PlayFab successfully
cloud.js?1120:76 PlayFab Connection Events Succeessful.
cloud.js?1120:76 PlayFab Connected: GoWish
save.js?1120:57 set force reload to 0
combatManager.js?1120:1 Combat Manager Built...
raidManager.js?1120:1 Golbin Raid Manager Built...
save.js?1120:14 Loading Save Game...
save.js?1120:14 Save Game Loaded...
main.js?1120:5 Game Loaded
cloud.js?1120:8 Synchronising with Cloud
index.html:559 GET https://melvoridle.com/assets/js/plugins/chart.js/Chart.bundle.min.js net::ERR_ABORTED 404
cloud.js?1120:76 Connected to PlayFab successfully
cloud.js?1120:76 PlayFab Connection Events Succeessful.
index.html:559 GET https://melvoridle.com/assets/js/plugins/chart.js/Chart.bundle.min.js net::ERR_ABORTED 404
cloud.js?1120:76 PlayFab Connected: GoWish
oneui.core.min.js:6 jQuery.Deferred exception: Chart is not defined ReferenceError: Chart is not defined
    at Function.value (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:1316)
    at Function.value (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2626)
    at HTMLDocument.<anonymous> (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2705)
    at e (https://melvoridle.com/assets/js/oneui.core.min.js:6:29792)
    at t (https://melvoridle.com/assets/js/oneui.core.min.js:6:30116) undefined
C.Deferred.exceptionHook @ oneui.core.min.js:6
t @ oneui.core.min.js:6
setTimeout (async)
(anonymous) @ oneui.core.min.js:6
r @ oneui.core.min.js:6
fireWith @ oneui.core.min.js:6
fire @ oneui.core.min.js:6
r @ oneui.core.min.js:6
fireWith @ oneui.core.min.js:6
ready @ oneui.core.min.js:6
F @ oneui.core.min.js:6
oneui.core.min.js:6 Uncaught ReferenceError: Chart is not defined
    at Function.value (be_pages_dashboard.min.js:6)
    at Function.value (be_pages_dashboard.min.js:6)
    at HTMLDocument.<anonymous> (be_pages_dashboard.min.js:6)
    at e (oneui.core.min.js:6)
    at t (oneui.core.min.js:6)
value @ be_pages_dashboard.min.js:6
value @ be_pages_dashboard.min.js:6
(anonymous) @ be_pages_dashboard.min.js:6
e @ oneui.core.min.js:6
t @ oneui.core.min.js:6
setTimeout (async)
C.readyException @ oneui.core.min.js:6
(anonymous) @ oneui.core.min.js:6
e @ oneui.core.min.js:6
t @ oneui.core.min.js:6
setTimeout (async)
(anonymous) @ oneui.core.min.js:6
r @ oneui.core.min.js:6
fireWith @ oneui.core.min.js:6
fire @ oneui.core.min.js:6
r @ oneui.core.min.js:6
fireWith @ oneui.core.min.js:6
t @ oneui.core.min.js:6
setTimeout (async)
(anonymous) @ oneui.core.min.js:6
r @ oneui.core.min.js:6
fireWith @ oneui.core.min.js:6
fire @ oneui.core.min.js:6
r @ oneui.core.min.js:6
fireWith @ oneui.core.min.js:6
ready @ oneui.core.min.js:6
F @ oneui.core.min.js:6
sca.17.5.12.js:32 a: 0.002197265625 ms
```
I hope this is what you were looking for

**Are you using any scripts?**
I have no scripts or ad blockers active.

**Comment by austin-wiechman** [comment]
It appears to have been a bug with the version of Brave not retaining site settings. The issue has been resolved.
