### ISSUE TITLE
Failed to load

### ISSUE THREAD

**Issue by Nedyarg1100** [MelvorIdle/melvoridle.github.io#1392]
**Describe the bug**
Game failed to load

**To Reproduce**
1. Open app

**Expected behavior**
Game opens as normal

**Screenshots**
![Screenshot_20210929-115539_Melvor Idle](https://user-images.githubusercontent.com/87917058/135324731-e8fc2edf-9481-439d-841b-e7e3a0509187.jpg)

**Browser**
Android app
V 0.03.8

**Console output**
TypeError: Invalid value used as weak map key
    at WeakMap.set (<anonymous>)
    at l.e.init (https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6:211412)
    at new l (https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6:210695)
    at updateWindow (https://android.melvoridle.com/assets/js/game/main.js?1169:1:14197)
    at finaliseLoad (https://android.melvoridle.com/assets/js/game/main.js?1169:341:1)
    at selectCharacter (https://android.melvoridle.com/assets/js/game/main.js?1169:331:223)
    at onloadEvent (https://android.melvoridle.com/assets/js/game/save.js?1169:60:267)
    at https://android.melvoridle.com/assets/js/game/save.js?1169:64:121

**Are you using any scripts?**
Nope

**Comment by MelvorIdle** [comment]
I believe this has been fixed. Please open a new bug report if it has not
