### ISSUE TITLE
Passive cooking doesn't need available ingredients

### ISSUE THREAD

**Issue by ohrius** [MelvorIdle/melvoridle.github.io#1393]
**Describe the bug**
Offline progression will offer rewards to stockpile, even while out of one or more resources. 

**To Reproduce**
1. Start active cooking on cooking fire. 
2. Then start passive cooking on another workstation (pot or furnace). Choose a recipe where one or more ingredients is missing.
3. Switch to another tab or close the game.
4. When offline progression is calculating rewards, passive
5. Using magic cooking fire, magic furnace and magic pot. 

**Expected behavior**
As much rewards as ingredients allow in time given. The "not enoug resources" error is shown"

**Screenshots**
![image](https://user-images.githubusercontent.com/9296155/135325947-bf76ba43-26b0-4603-a361-525330054d73.png)
Have never gathered any chicken legs after update, but the amount of chicken soup in stockpile is increasing while offline. 

**Browser**
Chrome  93.0.4577.82 64 bit

**Console output**
www.googletagmanager.com/gtag/js?id=UA-129674422-1:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
ads.adthrive.com/sites/5ea18421f87fa26d37d8fb62/ads.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
style.css:1 Failed to load resource: the server responded with a status of 404 ()
beacon.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
beacon.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
oneui.core.min.js:6 jQuery.Deferred exception: Chart is not defined ReferenceError: Chart is not defined
    at Function.value (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:1316)
    at Function.value (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2626)
    at HTMLDocument.<anonymous> (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2705)
    at e (https://melvoridle.com/assets/js/oneui.core.min.js:6:29792)
    at t (https://melvoridle.com/assets/js/oneui.core.min.js:6:30116) undefined
C.Deferred.exceptionHook @ oneui.core.min.js:6
oneui.core.min.js:6 Uncaught ReferenceError: Chart is not defined
beacon.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
cloud.js?1169:66 Connected to PlayFab successfully
save.js?1169:57 set force reload to 1
combatManager.js?1169:1 Combat Manager Built...
raidManager.js?1169:1 Golbin Raid Manager Built...
save.js?1169:14 Loading Save Game...
save.js?1169:14 Save Game Loaded...
main.js?1169:5 Game Loaded
beacon.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
beacon.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
oneui.core.min.js:6 jQuery.Deferred exception: Chart is not defined ReferenceError: Chart is not defined
    at Function.value (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:1316)
    at Function.value (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2626)
    at HTMLDocument.<anonymous> (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2705)
    at e (https://melvoridle.com/assets/js/oneui.core.min.js:6:29792)
    at t (https://melvoridle.com/assets/js/oneui.core.min.js:6:30116) undefined
C.Deferred.exceptionHook @ oneui.core.min.js:6
oneui.core.min.js:6 Uncaught ReferenceError: Chart is not defined
    at Function.value (be_pages_dashboard.min.js:6)
    at Function.value (be_pages_dashboard.min.js:6)
    at HTMLDocument.<anonymous> (be_pages_dashboard.min.js:6)
    at e (oneui.core.min.js:6)
    at t (oneui.core.min.js:6)
cloud.js?1169:66 Connected to PlayFab successfully
cloud.js?1169:8 Synchronising with Cloud
style.css:1 Failed to load resource: the server responded with a status of 404 ()
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/sm/57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/popper.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Are you using any scripts?**
Not using any scripts.

**Comment by coolrox95** [comment]
Fixed as of Beta v1.0.
