### ISSUE TITLE
Insta death on Farmer after thieving update.

### ISSUE THREAD

**Issue by cjarenwheeler** [MelvorIdle/melvoridle.github.io#1402]
**Describe the bug**

Username: IamBatman

I was thieving the farmer. I noticed I wasn't logged into the cloud. Clicked login and sent me to main page where my account was. Entered. AFK message said I was gone 8 seconds and had died at the farmer losing my amulet. I currently have 40k sharks in my attached inventory. Also, the damage farmer does is 4. No way to die in 8 seconds. Additionally, I lost trophy progression on my farmer after the update. 

**To Reproduce**
1. Go to 'thieving - farmer'
2. Click on 'farmer'
3. Scroll down to 'n/a'
4. See error - login to cloud after starting farmer. Go to main screen login. Login. Be dead. 

**Expected behavior**
Not to die in 8 seconds with 40k sharks in food slot. 

**Screenshots**

**Browser**
Please tell us what browser you are using and what version.
Chrome. v0.22

**Console output**
Please open the console by pressing F12 and copy it here.
Failed to load resource: the server responded with a status of 404 ()
www.googletagmanager.com/gtag/js?id=UA-129674422-1:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
ads.adthrive.com/sites/5ea18421f87fa26d37d8fb62/ads.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
beacon.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
beacon.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
beacon.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
oneui.core.min.js:6 jQuery.Deferred exception: Chart is not defined ReferenceError: Chart is not defined
    at Function.value (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:1316)
    at Function.value (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2626)
    at HTMLDocument.<anonymous> (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2705)
    at e (https://melvoridle.com/assets/js/oneui.core.min.js:6:29792)
    at t (https://melvoridle.com/assets/js/oneui.core.min.js:6:30116) undefined
C.Deferred.exceptionHook @ oneui.core.min.js:6
oneui.core.min.js:6 Uncaught ReferenceError: Chart is not defined
cloud.js?1176:66 Connected to PlayFab successfully
cloud.js?1176:67 PlayFab Connected: CaddyShacks
save.js?1176:57 set force reload to 0
combatManager.js?1176:1 Combat Manager Built...
raidManager.js?1176:1 Golbin Raid Manager Built...
save.js?1176:14 Loading Save Game...
save.js?1176:14 Save Game Loaded...
main.js?1176:5 Game Loaded
cloud.js?1176:8 Synchronising with Cloud
cloud.js?1176:66 Connected to PlayFab successfully
beacon.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
beacon.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
oneui.core.min.js:6 jQuery.Deferred exception: Chart is not defined ReferenceError: Chart is not defined
    at Function.value (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:1316)
    at Function.value (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2626)
    at HTMLDocument.<anonymous> (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2705)
    at e (https://melvoridle.com/assets/js/oneui.core.min.js:6:29792)
    at t (https://melvoridle.com/assets/js/oneui.core.min.js:6:30116) undefined
C.Deferred.exceptionHook @ oneui.core.min.js:6
oneui.core.min.js:6 Uncaught ReferenceError: Chart is not defined
    at Function.value (be_pages_dashboard.min.js:6)
    at Function.value (be_pages_dashboard.min.js:6)
    at HTMLDocument.<anonymous> (be_pages_dashboard.min.js:6)
    at e (oneui.core.min.js:6)
    at t (oneui.core.min.js:6)
cloud.js?1176:67 PlayFab Connected: CaddyShacks
style.css:1 Failed to load resource: the server responded with a status of 404 ()
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/popper.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/sm/57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Are you using any scripts?**
Nope.
Please let us know if you are using scripts the time this bug occurred.

**Comment by cjarenwheeler** [comment]
I am currently 10 hp on this account. I forgot to mention. However, I have bought all auto eat and was gone for 8 seconds. Stun damage is 4. But 8 seconds death?

**Comment by cjarenwheeler** [comment]
Also just noticed you changed the max damage hit on them. Please disregard my bug. Trying to figure out how to delete it.
