### ISSUE TITLE
Offline Thieving and Combat During Golbin Raid Not Working

### ISSUE THREAD

**Issue by BrisingrChetowa** [MelvorIdle/melvoridle.github.io#1427]
**Describe the bug**
While Golbin Raiding, offline progress in Combat and Thieving isn't working. I'll come back after hours only to have a pop-up saying I was gone 0 seconds, no progress. Normal crafting works, though.

**To Reproduce**
1. Start a combat.
2. Go to Golbin Raid.
3. Raid for any period of time.
4. Leave raid, and come back to no progress.

**Expected behavior**
Progress to be made. Sorry, not trying to be snarky or sarcastic. Just answering.

**Screenshots**
![No Progress](https://user-images.githubusercontent.com/49105254/135943040-1c2a8dfc-a6bf-471e-b869-6a775c8faed9.png)

**Browser**
This has happened on both Steam and my Android phone. Steam version Alpha 0.22 (?1180). Same version on Android.

**Console output**
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
style.css:1 Failed to load resource: the server responded with a status of 404 ()
c.amazon-adsystem.com/aax2/apstag.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
adthrive.min.js?threshold=0&deployment=ad-1249:pr1853:flex-06:cea01a0:con&cb=1633394974131:3 AmazonBootstrap::load  Error: Failed to import script https://c.amazon-adsystem.com/aax2/apstag.js
    at HTMLScriptElement.<anonymous> (adthrive.min.js?threshold=0&deployment=ad-1249:pr1853:flex-06:cea01a0:con&cb=1633394974131:3)
e.call @ adthrive.min.js?threshold=0&deployment=ad-1249:pr1853:flex-06:cea01a0:con&cb=1633394974131:3
securepubads.g.doubleclick.net/tag/js/gpt.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
adthrive.min.js?threshold=0&deployment=ad-1249:pr1853:flex-06:cea01a0:con&cb=1633394974131:3 GAMBootstrap::sendScript  Error: Failed to import script https://securepubads.g.doubleclick.net/tag/js/gpt.js
    at HTMLScriptElement.<anonymous> (adthrive.min.js?threshold=0&deployment=ad-1249:pr1853:flex-06:cea01a0:con&cb=1633394974131:3)
e.call @ adthrive.min.js?threshold=0&deployment=ad-1249:pr1853:flex-06:cea01a0:con&cb=1633394974131:3
prebid.min.js:1 fun-hooks: referenced 'registerAdserver' but it was never created
(anonymous) @ prebid.min.js:1
prebid.min.js:1 fun-hooks: referenced 'adpod' but it was never created
(anonymous) @ prebid.min.js:1
oneui.core.min.js:6 jQuery.Deferred exception: Chart is not defined ReferenceError: Chart is not defined
    at Function.value (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:1316)
    at Function.value (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2626)
    at HTMLDocument.<anonymous> (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2705)
    at e (https://melvoridle.com/assets/js/oneui.core.min.js:6:29792)
    at t (https://melvoridle.com/assets/js/oneui.core.min.js:6:30116) undefined
C.Deferred.exceptionHook @ oneui.core.min.js:6
oneui.core.min.js:6 Uncaught ReferenceError: Chart is not defined
    at Function.value (be_pages_dashboard.min.js:6)
    at Function.value (be_pages_dashboard.min.js:6)
    at HTMLDocument.<anonymous> (be_pages_dashboard.min.js:6)
    at e (oneui.core.min.js:6)
    at t (oneui.core.min.js:6)
oneui.core.min.js:6 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
send @ oneui.core.min.js:6
combatManager.js?1180:1 Combat Manager Built...
raidManager.js?1180:1 Golbin Raid Manager Built...
adthrive.min.js?threshold=0&deployment=ad-1249:pr1853:flex-06:cea01a0:con&cb=1633394974131:3 LayoutShiftComponent::logLayoutShift  Array(3)
adthrive.min.js?threshold=0&deployment=ad-1249:pr1853:flex-06:cea01a0:con&cb=1633394974131:3 WebVitalsComponent::logWebVital  Object
cloud.js?1180:66 Connected to PlayFab successfully
oneui.core.min.js:6 jQuery.Deferred exception: Chart is not defined ReferenceError: Chart is not defined
    at Function.value (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:1316)
    at Function.value (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2626)
    at HTMLDocument.<anonymous> (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2705)
    at e (https://melvoridle.com/assets/js/oneui.core.min.js:6:29792)
    at t (https://melvoridle.com/assets/js/oneui.core.min.js:6:30116) undefined
C.Deferred.exceptionHook @ oneui.core.min.js:6
oneui.core.min.js:6 Uncaught ReferenceError: Chart is not defined
    at Function.value (be_pages_dashboard.min.js:6)
    at Function.value (be_pages_dashboard.min.js:6)
    at HTMLDocument.<anonymous> (be_pages_dashboard.min.js:6)
    at e (oneui.core.min.js:6)
    at t (oneui.core.min.js:6)
cloud.js?1180:67 PlayFab Connected: BrisingrChetowa
save.js?1180:57 set force reload to 0
combatManager.js?1180:1 Combat Manager Built...
raidManager.js?1180:1 Golbin Raid Manager Built...
save.js?1180:14 Loading Save Game...
save.js?1180:14 Save Game Loaded...
main.js?1180:5 Game Loaded
cloud.js?1180:8 Synchronising with Cloud
cloud.js?1180:66 Connected to PlayFab successfully
oneui.core.min.js:6 jQuery.Deferred exception: Chart is not defined ReferenceError: Chart is not defined
    at Function.value (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:1316)
    at Function.value (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2626)
    at HTMLDocument.<anonymous> (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2705)
    at e (https://melvoridle.com/assets/js/oneui.core.min.js:6:29792)
    at t (https://melvoridle.com/assets/js/oneui.core.min.js:6:30116) undefined
C.Deferred.exceptionHook @ oneui.core.min.js:6
oneui.core.min.js:6 Uncaught ReferenceError: Chart is not defined
    at Function.value (be_pages_dashboard.min.js:6)
    at Function.value (be_pages_dashboard.min.js:6)
    at HTMLDocument.<anonymous> (be_pages_dashboard.min.js:6)
    at e (oneui.core.min.js:6)
    at t (oneui.core.min.js:6)
cloud.js?1180:67 PlayFab Connected: BrisingrChetowa
style.css:1 Failed to load resource: the server responded with a status of 404 ()
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/sm/57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/popper.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Are you using any scripts?**
I'm just using the game as presented. Nothing special added in.

**Comment by coolrox95** [comment]
Fixed as of Beta v1.0.
