### ISSUE TITLE
Couldn't Record Offline Progress Bug

### ISSUE THREAD

**Issue by SemaNamTV** [MelvorIdle/melvoridle.github.io#1439]
**Describe the bug**
After going offline, the game couldn't record my offline progress properly and stopped the skill completely

**To Reproduce**
Honestly, I can barely remember what I did the last time I was online.
I believe I just closed the tab when I went offline

**Expected behavior**
Expected to continue cooking offline.

**Screenshots**
No Screenshots, but I got this error message asking me to report the bug:

Skill:null
Action: null
Timestamp: null

TypeError: Cannot read propertiers of null (reading 'passive') at https://melvoridle.com/assets/js/game/main.js?1183:164:380

**Browser**
Google Chrome Version 94.0.4606.71 (Official Build) (64-bit)

**Console output**
I am personally not savvy with this information, I am unsure what is relevant or what is not, so i just copied everything.

style.css:1 Failed to load resource: the server responded with a status of 404 ()
ads.adthrive.com/sites/5ea18421f87fa26d37d8fb62/ads.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
oneui.core.min.js:6 jQuery.Deferred exception: Chart is not defined ReferenceError: Chart is not defined
    at Function.value (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:1316)
    at Function.value (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2626)
    at HTMLDocument.<anonymous> (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2705)
    at e (https://melvoridle.com/assets/js/oneui.core.min.js:6:29792)
    at t (https://melvoridle.com/assets/js/oneui.core.min.js:6:30116) undefined
C.Deferred.exceptionHook @ oneui.core.min.js:6
5Unchecked runtime.lastError: The message port closed before a response was received.
oneui.core.min.js:6 Uncaught ReferenceError: Chart is not defined
    at Function.value (be_pages_dashboard.min.js:6)
    at Function.value (be_pages_dashboard.min.js:6)
    at HTMLDocument.<anonymous> (be_pages_dashboard.min.js:6)
    at e (oneui.core.min.js:6)
    at t (oneui.core.min.js:6)
cloud.js?1183:66 Connected to PlayFab successfully
save.js?1183:57 set force reload to 0
cloud.js?1183:67 PlayFab Connected: Semanam
combatManager.js?1183:1 Combat Manager Built...
raidManager.js?1183:1 Golbin Raid Manager Built...
save.js?1183:14 Loading Save Game...
save.js?1183:14 Save Game Loaded...
main.js?1183:5 Game Loaded
cloud.js?1183:66 Connected to PlayFab successfully
oneui.core.min.js:6 jQuery.Deferred exception: Chart is not defined ReferenceError: Chart is not defined
    at Function.value (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:1316)
    at Function.value (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2626)
    at HTMLDocument.<anonymous> (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2705)
    at e (https://melvoridle.com/assets/js/oneui.core.min.js:6:29792)
    at t (https://melvoridle.com/assets/js/oneui.core.min.js:6:30116) undefined
C.Deferred.exceptionHook @ oneui.core.min.js:6
oneui.core.min.js:6 Uncaught ReferenceError: Chart is not defined
    at Function.value (be_pages_dashboard.min.js:6)
    at Function.value (be_pages_dashboard.min.js:6)
    at HTMLDocument.<anonymous> (be_pages_dashboard.min.js:6)
    at e (oneui.core.min.js:6)
    at t (oneui.core.min.js:6)
cloud.js?1183:67 PlayFab Connected: Semanam
cloud.js?1183:8 Synchronising with Cloud
style.css:1 Failed to load resource: the server responded with a status of 404 ()
DevTools failed to load source map: Could not load content for chrome-extension://alplpnakfeabeiebipdmaenpmbgknjce/include.preload.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load source map: Could not load content for chrome-extension://alplpnakfeabeiebipdmaenpmbgknjce/include.postload.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/sm/57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/popper.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Are you using any scripts?**
N/A

**Comment by MelvorIdle** [comment]
I believe this has been fixed. Please open a new bug report if it has not
