### ISSUE TITLE
Can't load any save files

### ISSUE THREAD

**Issue by Alquamos** [MelvorIdle/melvoridle.github.io#1482]
**Describe the bug**
As with similar posters here, in my case I could not load any of my save files. Local or cloud saves. The game would load infinitely. After restarting the game, it would then attempt to fix the save, but no luck there. I did restart the computer/Steam, verify game files, even did sfc /scannow. Nothing helps. 

Error code:
TypeError: Invalid value used as weak map key
    at WeakMap.set (<anonymous>)
    at l.e.init (https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6:211412)
    at new l (https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6:210695)
    at updateWindow (https://steam.melvoridle.com/assets/js/game/main.js?1186:1:14199)
    at finaliseLoad (https://steam.melvoridle.com/assets/js/game/main.js?1186:341:1)
    at selectCharacter (https://steam.melvoridle.com/assets/js/game/main.js?1186:331:223)
    at onloadEvent (https://steam.melvoridle.com/assets/js/game/save.js?1186:61:267)
    at https://steam.melvoridle.com/assets/js/game/save.js?1186:65:121

**Screenshots**

![2021-10-19 (2)](https://user-images.githubusercontent.com/12535222/137939014-2906e671-4906-4cdb-bbdb-f4fdd40ea18e.png)

**Browser**
Steam

**Console output**
?

**Are you using any scripts?**
No

**Comment by MelvorIdle** [comment]
I believe this has been fixed. Please open a new bug report if it has not
