### ISSUE TITLE
[Bug]: Offline Smithing bug

### ISSUE THREAD

**Issue by cb8537** [MelvorIdle/melvoridle.github.io#1554]
### Describe the bug

Was offline smithing making platelegs (I think), Logged back in and got the error 

### Reproduction Steps

1)Smithing
2)Logged off
3)Logged in
4)Bug

### Expected behaviour

Error not happening

### Screenshots

![image](https://user-images.githubusercontent.com/43388391/139940604-2c7e7b94-e6b2-4e1f-9056-435417057183.png)

### Console output

TypeError: Cannot read properties of undefined (reading 'smithReq')
    at checkSmithingReq (smithing2.js?1209:13)
    at main.js?1209:225
(anonymous) @ main.js?1209:256
MICSR.js:26 MICSR: setting up main
beacon.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
beacon.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
index_noads.php:1 Uncaught (in promise) Error processing offline in-timeout
oneui.core.min.js:6 jQuery.Deferred exception: Chart is not defined ReferenceError: Chart is not defined
    at Function.value (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:1316)
    at Function.value (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2626)
    at HTMLDocument.<anonymous> (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2705)
    at e (https://melvoridle.com/assets/js/oneui.core.min.js:6:29792)
    at t (https://melvoridle.com/assets/js/oneui.core.min.js:6:30116) undefined
C.Deferred.exceptionHook @ oneui.core.min.js:6
oneui.core.min.js:6 Uncaught ReferenceError: Chart is not defined
    at Function.value (be_pages_dashboard.min.js:6)
    at Function.value (be_pages_dashboard.min.js:6)
    at HTMLDocument.<anonymous> (be_pages_dashboard.min.js:6)
    at e (oneui.core.min.js:6)
    at t (oneui.core.min.js:6)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Alpha v0.21

### Game Subversion

?1209

### Are you using any scripts or extensions?

Yes

**Comment by MelvorIdle** [comment]
It looks like you were using the Superheat spell while offline in Alt. Magic.

What bar did you select with the Magic spell?

**Comment by cb8537** [comment]
Mithril iirc

**Comment by MelvorIdle** [comment]
I believe this issue it now fixed.
