### ISSUE TITLE
[Bug]: Can't log in on steam client or browser

### ISSUE THREAD

**Issue by gioZimu** [MelvorIdle/melvoridle.github.io#1564]
### Describe the bug

Not able to login on steam client or browser, receive "Invalid Login". 

Account works fine on mobile. Never really played on mobile, so first login attempt was through steam client. 

Changed password through forgot password button, still only able to login on mobile.

### Reproduction Steps

1. Go to www.melvoridle.com
2. Type in account and password
3. Click Login button
4. See "Invalid login" message

### Expected behaviour

Expected login to go through and game to load.

### Screenshots

https://i.imgur.com/RCxO4wp.png

### Console output

oneui.core.min.js:6 jQuery.Deferred exception: Cannot read properties of undefined (reading 'setDefaults') TypeError: Cannot read properties of undefined (reading 'setDefaults')
    at Function.value (https://melvoridle.com/assets/js/oneui.app.min.js:6:18346)
    at Object.validation (https://melvoridle.com/assets/js/oneui.app.min.js:6:3612)
    at Function.value (https://melvoridle.com/assets/js/oneui.app.min.js:6:3742)
    at t.value (https://melvoridle.com/assets/js/oneui.app.min.js:6:31844)
    at Function.value (https://melvoridle.com/assets/js/pages/op_auth_signin.min.js:6:1332)
    at Function.value (https://melvoridle.com/assets/js/pages/op_auth_signin.min.js:6:1774)
    at HTMLDocument.<anonymous> (https://melvoridle.com/assets/js/pages/op_auth_signin.min.js:6:1857)
    at e (https://melvoridle.com/assets/js/oneui.core.min.js:6:29792)
    at t (https://melvoridle.com/assets/js/oneui.core.min.js:6:30116) undefined
C.Deferred.exceptionHook @ oneui.core.min.js:6
oneui.core.min.js:6 Uncaught TypeError: Cannot read properties of undefined (reading 'setDefaults')
    at Function.value (oneui.app.min.js:6)
    at Object.validation (oneui.app.min.js:6)
    at Function.value (oneui.app.min.js:6)
    at t.value (oneui.app.min.js:6)
    at Function.value (op_auth_signin.min.js:6)
    at Function.value (op_auth_signin.min.js:6)
    at HTMLDocument.<anonymous> (op_auth_signin.min.js:6)
    at e (oneui.core.min.js:6)
    at t (oneui.core.min.js:6)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Alpha v0.22.1

### Game Subversion

can't see this without logging in 

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Can you confirm you are still seeing this bug?

Please ensure you are using your username to log in, and not your email.

**Comment by gioZimu** [comment]
Yeah, still seeing this bug. Using username and not email

**Comment by MelvorIdle** [comment]
Can you please attempt another password reset.

Please use the exact username provided inside the email you receive.

**Comment by gioZimu** [comment]
Yep, that was it. I'm stupid and turns out username was wrong. So sorry for hassle.
