### ISSUE TITLE
[Bug]: Bone Necklace functions normally when Prayer skill not unlocked

### ISSUE THREAD

**Issue by liththedev** [MelvorIdle/melvoridle.github.io#1577]
### Describe the bug

On an adventure character without Prayer unlocked, the bone necklace automatically buries bones (for 2x points). If you can't bury bones manually, I wouldn't expect to be able to bury bones automatically.

### Reproduction Steps

1. Create new adventure character
2. don't unlock Prayer skill
3. obtain/equip Bone Necklace
4. kill monsters that drop bones

### Expected behaviour

Bones go to the loot box, as if no bone necklace was equipped.

### Console output

```Failed to load resource: the server responded with a status of 404 ()
​ jQuery.Deferred exception: Chart is not defined ReferenceError: Chart is not defined
    at Function.value (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:1316)
    at Function.value (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2626)
    at HTMLDocument.<anonymous> (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2705)
    at e (https://melvoridle.com/assets/js/oneui.core.min.js:6:29792)
    at t (https://melvoridle.com/assets/js/oneui.core.min.js:6:30116) undefined
C.Deferred.exceptionHook @ oneui.core.min.js:6
oneui.core.min.js:6 Uncaught ReferenceError: Chart is not defined
save.js?1215:54 set force reload to 1
combatManager.js?1215:1 Combat Manager Built...
raidManager.js?1215:1 Golbin Raid Manager Built...
save.js?1215:14 Loading Save Game...
save.js?1215:14 Save Game Loaded...
main.js?1215:5 Game Loaded
oneui.core.min.js:6 jQuery.Deferred exception: Chart is not defined ReferenceError: Chart is not defined
    at Function.value (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:1316)
    at Function.value (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2626)
    at HTMLDocument.<anonymous> (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2705)
    at e (https://melvoridle.com/assets/js/oneui.core.min.js:6:29792)
    at t (https://melvoridle.com/assets/js/oneui.core.min.js:6:30116) undefined
C.Deferred.exceptionHook @ oneui.core.min.js:6
oneui.core.min.js:6 Uncaught ReferenceError: Chart is not defined
    at Function.value (be_pages_dashboard.min.js:6)
    at Function.value (be_pages_dashboard.min.js:6)
    at HTMLDocument.<anonymous> (be_pages_dashboard.min.js:6)
    at e (oneui.core.min.js:6)
    at t (oneui.core.min.js:6)
style.css:1 Failed to load resource: the server responded with a status of 404 ()
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/sm/57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/popper.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE```

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Alpha v0.22.1

### Game Subversion

1215

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
This is now fixed
