### ISSUE TITLE
[Bug]: Stuck Mining

### ISSUE THREAD

**Issue by Qlmmb2086** [MelvorIdle/melvoridle.github.io#1607]
### Describe the bug

Mining progress bar fills but then gets stuck at 100% without resetting/producing ore.

### Reproduction Steps

[Mining Bug Export.txt](https://github.com/MelvorIdle/melvoridle.github.io/files/7517874/Mining.Bug.Export.txt)

Load exported save, click any mining node (probably)

### Console output

Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
style.css:1 Failed to load resource: the server responded with a status of 404 ()
beacon.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
beacon.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
oneui.core.min.js:6 jQuery.Deferred exception: Chart is not defined ReferenceError: Chart is not defined
    at Function.value (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:1316)
    at Function.value (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2626)
    at HTMLDocument.<anonymous> (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2705)
    at e (https://melvoridle.com/assets/js/oneui.core.min.js:6:29792)
    at t (https://melvoridle.com/assets/js/oneui.core.min.js:6:30116) undefined
C.Deferred.exceptionHook @ oneui.core.min.js:6
oneui.core.min.js:6 Uncaught ReferenceError: Chart is not defined
    at Function.value (be_pages_dashboard.min.js:6)
    at Function.value (be_pages_dashboard.min.js:6)
    at HTMLDocument.<anonymous> (be_pages_dashboard.min.js:6)
    at e (oneui.core.min.js:6)
    at t (oneui.core.min.js:6)
beacon.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
cloud.js?1268:65 Connected to PlayFab successfully
cloud.js?1268:66 PlayFab Connected: Morhe
save.js?1268:58 set force reload to 4
combatManager.js?1268:1 Combat Manager Built...
raidManager.js?1268:1 Golbin Raid Manager Built...
save.js?1268:14 Loading Save Game...
save.js?1268:14 Save Game Loaded...
main.js?1268:8 Game Loaded
beacon.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
beacon.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
oneui.core.min.js:6 jQuery.Deferred exception: Chart is not defined ReferenceError: Chart is not defined
    at Function.value (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:1316)
    at Function.value (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2626)
    at HTMLDocument.<anonymous> (https://melvoridle.com/assets/js/pages/be_pages_dashboard.min.js:6:2705)
    at e (https://melvoridle.com/assets/js/oneui.core.min.js:6:29792)
    at t (https://melvoridle.com/assets/js/oneui.core.min.js:6:30116) undefined
C.Deferred.exceptionHook @ oneui.core.min.js:6
oneui.core.min.js:6 Uncaught ReferenceError: Chart is not defined
    at Function.value (be_pages_dashboard.min.js:6)
    at Function.value (be_pages_dashboard.min.js:6)
    at HTMLDocument.<anonymous> (be_pages_dashboard.min.js:6)
    at e (oneui.core.min.js:6)
    at t (oneui.core.min.js:6)
cloud.js?1268:65 Connected to PlayFab successfully
cloud.js?1268:66 PlayFab Connected: Morhe
cloud.js?1268:7 Synchronising with Cloud
save.js?1268:17 Uncaught TypeError: Cannot set properties of null (setting 'value')
    at exportSave (save.js?1268:17)
    at HTMLButtonElement.onclick (index_noads.php:1)
style.css:1 Failed to load resource: the server responded with a status of 404 ()
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/popper.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/sm/57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

Beta v1.0

### Game Subversion

?1268

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Importing the save worked as intended for me. All available Mining nodes can be mined without error.

Can you confirm you are still seeing this error? You can also try reimporting the save yourself which might fix it.

**Comment by Qlmmb2086** [comment]
Hmm... refreshing to v1272 seems to have fixed it, even without the reimport. Strange.
