### ISSUE TITLE
My save broke

### ISSUE THREAD

**Issue by Biongra** [MelvorIdle/melvoridle.github.io#1890]
### Describe the bug

My save not load.

### Screenshots

![Melvor](https://user-images.githubusercontent.com/95729357/145137367-93d9d0a6-1ea2-4829-b34f-4ed2a8148bd8.JPG)

### Console output

TypeError: combatMenus.eventMenu.setButtonCallbacks is not a function
    at CombatManager.initialize (https://steam.melvoridle.com/assets/js/built/combatManager.js?1362:22:23)
    at updateWindow (https://steam.melvoridle.com/assets/js/game/main.js?1362:4:473)
    at finaliseLoad (https://steam.melvoridle.com/assets/js/game/main.js?1362:374:1)
    at selectCharacter (https://steam.melvoridle.com/assets/js/game/main.js?1362:365:221)
    at onloadEvent (https://steam.melvoridle.com/assets/js/game/save.js?1362:61:217)
    at HTMLDivElement.<anonymous> (https://steam.melvoridle.com/assets/js/game/save.js?1362:65:603)
    at HTMLDivElement.<anonymous> (https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6:84821)
    at Function.each (https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6:2967)
    at C.fn.init.each (https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6:1453)
    at Object.<anonymous> (https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6:84803)

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

v1.0

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Is this error still occurring?

**Comment by KristuMalta** [comment]
Mine is still occurring. buy only on my pc..the game works perfectly fine on mobile
