### ISSUE TITLE
[Bug]: Loading save file on Chrome freezes the page.

### ISSUE THREAD

**Issue by necrocw** [MelvorIdle/melvoridle.github.io#2131]
### Describe the bug

When entering the game from loading either a local or cloud file, the page freezes and is unpresonsive. Nothing is clickable in the game at least and if I were to wait, Chrome says the page is unresponsive and to either wait or kill the page. All other tabs on Chrome work. This does NOT happen to me on Firefox. I have tried clearing cache and cookies however the issue still persists. The issue happens after creating a new character.

### Reproduction Steps

Assuming you're signed in:
1. Click on the save file
2. When loading into the game, page freezes.

### Expected behaviour

When loading a save file, load into the game is play it.

### Screenshots

https://streamable.com/e3lsxe

### Console output

index_noads.php:44 GET https://melvoridle.com/style.css?2 net::ERR_ABORTED 404
index_noads.php:6 GET https://www.googletagmanager.com/gtag/js?id=UA-129674422-1 net::ERR_BLOCKED_BY_CLIENT
index_noads.php:2903 GET https://static.cloudflareinsights.com/beacon.min.js/v652eace1692a40cfa3763df669d7439c1639079717194 net::ERR_BLOCKED_BY_CLIENT
index_noads.php:2894 GET https://melvoridle.com/assets/js/game/languageJSON.js?1523 net::ERR_ABORTED 404
index_noads.php:2894 GET https://melvoridle.com/assets/js/game/languageJSON.js?1523 net::ERR_ABORTED 404
index.html:549 GET https://static.cloudflareinsights.com/beacon.min.js/v652eace1692a40cfa3763df669d7439c1639079717194 net::ERR_BLOCKED_BY_CLIENT
cloud.js?1523:71 Connected to PlayFab successfully
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/sm/57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/popper.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
save.js?1523:70 set force reload to 0
combatManager.js?1523:1 Combat Manager Built...
raidManager.js?1523:1 Golbin Raid Manager Built...
save.js?1523:15 Loading Save Game...
save.js?1523:15 Save Game Loaded...
main.js?1523:6 Game Loaded
VM165:140 Melvor ETA: loading...
VM165:384 Uncaught TypeError: Cannot read properties of null (reading 'parentNode')
    at Object.ETA.makeProcessingDisplays (<anonymous>:384:18)
    at loadETA (<anonymous>:2529:13)
    at startETA (<anonymous>:18:13)
    at loadScript (<anonymous>:2589:13)
ETA.makeProcessingDisplays @ VM165:384
loadETA @ VM165:2529
startETA @ VM165:18
loadScript @ VM165:2589
VM169:2 Melvor Items Drop Rates: Loaded
VM169:3 Melvor Items Drop Rates Contact: Polfy#6924
VM163:623 Show Modifiers: unknown modifier increasedGPFromFiremaking
VM163:623 Show Modifiers: unknown modifier decreasedGPFromFiremaking
VM163:623 Show Modifiers: no non-existent modifiers detected!
cloud.js?1523:71 Connected to PlayFab successfully
VM165:2502 ReferenceError: trees is not defined
    at gatheringWrapper (<anonymous>:527:21)
    at Object.ETA.timeRemainingWrapper (<anonymous>:508:17)
    at updateSkillWindow (<anonymous>:2500:21)
    at Object.set value [as value] (settings.js?1523:3:2432)
    at settings.js?1523:8:172
    at Array.forEach (<anonymous>)
    at loadCurrentSettings (settings.js?1523:8:67)
    at loadCloudOptions (cloud.js?1523:62:164)
    at Object.<anonymous> (cloud.js?1523:7:17)
    at r (oneui.core.min.js:6:28083)
updateSkillWindow @ VM165:2502
set value @ settings.js?1523:3
(anonymous) @ settings.js?1523:8
loadCurrentSettings @ settings.js?1523:8
loadCloudOptions @ cloud.js?1523:62
(anonymous) @ cloud.js?1523:7
r @ oneui.core.min.js:6
fireWith @ oneui.core.min.js:6
c @ oneui.core.min.js:6
(anonymous) @ oneui.core.min.js:6
VM165:2502 ReferenceError: selectedSmith is not defined
    at Object.ETA.timeRemainingWrapper (<anonymous>:471:21)
    at updateSkillWindow (<anonymous>:2500:21)
    at Object.set value [as value] (settings.js?1523:3:2432)
    at settings.js?1523:8:172
    at Array.forEach (<anonymous>)
    at loadCurrentSettings (settings.js?1523:8:67)
    at loadCloudOptions (cloud.js?1523:62:164)
    at Object.<anonymous> (cloud.js?1523:7:17)
    at r (oneui.core.min.js:6:28083)
    at Object.fireWith [as resolveWith] (oneui.core.min.js:6:28851)
updateSkillWindow @ VM165:2502
set value @ settings.js?1523:3
(anonymous) @ settings.js?1523:8
loadCurrentSettings @ settings.js?1523:8
loadCloudOptions @ cloud.js?1523:62
(anonymous) @ cloud.js?1523:7
r @ oneui.core.min.js:6
fireWith @ oneui.core.min.js:6
c @ oneui.core.min.js:6
(anonymous) @ oneui.core.min.js:6
VM165:2502 ReferenceError: selectedAltMagic is not defined
    at Object.ETA.timeRemainingWrapper (<anonymous>:491:21)
    at updateSkillWindow (<anonymous>:2500:21)
    at Object.set value [as value] (settings.js?1523:3:2432)
    at settings.js?1523:8:172
    at Array.forEach (<anonymous>)
    at loadCurrentSettings (settings.js?1523:8:67)
    at loadCloudOptions (cloud.js?1523:62:164)
    at Object.<anonymous> (cloud.js?1523:7:17)
    at r (oneui.core.min.js:6:28083)
    at Object.fireWith [as resolveWith] (oneui.core.min.js:6:28851)
updateSkillWindow @ VM165:2502
set value @ settings.js?1523:3
(anonymous) @ settings.js?1523:8
loadCurrentSettings @ settings.js?1523:8
loadCloudOptions @ cloud.js?1523:62
(anonymous) @ cloud.js?1523:7
r @ oneui.core.min.js:6
fireWith @ oneui.core.min.js:6
c @ oneui.core.min.js:6
(anonymous) @ oneui.core.min.js:6
VM165:2502 ReferenceError: selectedHerblore is not defined
    at Object.ETA.timeRemainingWrapper (<anonymous>:496:21)
    at updateSkillWindow (<anonymous>:2500:21)
    at Object.set value [as value] (settings.js?1523:3:2432)
    at settings.js?1523:8:172
    at Array.forEach (<anonymous>)
    at loadCurrentSettings (settings.js?1523:8:67)
    at loadCloudOptions (cloud.js?1523:62:164)
    at Object.<anonymous> (cloud.js?1523:7:17)
    at r (oneui.core.min.js:6:28083)
    at Object.fireWith [as resolveWith] (oneui.core.min.js:6:28851)
updateSkillWindow @ VM165:2502
set value @ settings.js?1523:3
(anonymous) @ settings.js?1523:8
loadCurrentSettings @ settings.js?1523:8
loadCloudOptions @ cloud.js?1523:62
(anonymous) @ cloud.js?1523:7
r @ oneui.core.min.js:6
fireWith @ oneui.core.min.js:6
c @ oneui.core.min.js:6
(anonymous) @ oneui.core.min.js:6
index.html:549 GET https://static.cloudflareinsights.com/beacon.min.js/v652eace1692a40cfa3763df669d7439c1639079717194 net::ERR_BLOCKED_BY_CLIENT

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.2

### Game Subversion

?1523

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
You have the ETA script enabled. This causes the game to break unless it is updated.

Please disable it. I can see based on the console log that it is enabled.
