### ISSUE TITLE
[Bug]: Cannot equip Ice Shield in adventure mode

### ISSUE THREAD

**Issue by AnaisJin** [MelvorIdle/melvoridle.github.io#2273]
### Describe the bug

I cannot equip the ice shield in adventure mode, while ranged combat is locked. I expect it is because ice shield is considered a ranged shield which makes no sense

### Reproduction Steps

in adventure mode, try and equip ice shield, while ranged combat is still locked

### Expected behaviour

Ice Shield being equipped

### Screenshots

![image](https://user-images.githubusercontent.com/53521622/156334264-2288e60f-9e7e-4455-bde6-ad0b70fd171b.png)

### Console output

style.css:1          Failed to load resource: the server responded with a status of 404 ()
www.googletagmanager.com/gtag/js?id=UA-129674422-1:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
v652eace1692a40cfa3763df669d7439c1639079717194:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
v652eace1692a40cfa3763df669d7439c1639079717194:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
cloud.js?1819:67 Connected to PlayFab successfully
2cloud.js?1819:75 Uncaught TypeError: Cannot read properties of undefined (reading 'Value')
    at cloud.js:75:355
    at XMLHttpRequest.xhr.onloadend (PlayFabClientApi.js:101:25)
save.js?1819:71 set force reload to 1
combatManager.js?1819:1 Combat Manager Built...
raidManager.js?1819:1 Golbin Raid Manager Built...
save.js?1819:15 Loading Save Game...
save.js?1819:15 Save Game Loaded...
main.js?1819:6 Game Loaded
cloud.js?1819:67 Connected to PlayFab successfully
v652eace1692a40cfa3763df669d7439c1639079717194:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
cloud.js?1819:68 PlayFab Connected: theidler
cloud.js?1819:11 Synchronising with Cloud
2cloud.js?1819:75 Uncaught TypeError: Cannot read properties of undefined (reading 'Value')
    at cloud.js:75:355
    at XMLHttpRequest.xhr.onloadend (PlayFabClientApi.js:101:25)
style.css:1          Failed to load resource: the server responded with a status of 404 ()
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/popper.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/sm/57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1819

### Are you using any scripts or extensions?

No

**Comment by Gnomeball** [comment]
This isn't a bug, the ice Shield requires level 40 Ranged to equip.

**Comment by AnaisJin** [comment]
Ah, missed that. Thank you
