### ISSUE TITLE
[Bug]: Offline Rewards Stuck

### ISSUE THREAD

**Issue by msluga13** [MelvorIdle/melvoridle.github.io#2412]
### Describe the bug

Describe the bug
I have this issue on iOS and on the website. I login and select a save which enters me into the game. A popup saying loading offline progress appears and never succeeds (on web it seems like its looping). It appears to be an issue with an offline timestamp.

### Reproduction Steps

1. Login

### Expected behaviour

Should provide offline rewards.

### Save Link

https://melvoridle.com/save/OP1pPGyp

### Console output

style.css:1          Failed to load resource: the server responded with a status of 404 ()
css:1          Failed to load resource: the server responded with a status of 403 ()
cloud.js?1875:67 Connected to PlayFab successfully
2cloud.js?1875:75 Uncaught TypeError: Cannot read properties of undefined (reading 'Value')
    at cloud.js?1875:75:355
    at XMLHttpRequest.xhr.onloadend (PlayFabClientApi.js:101:25)
style.css:1          Failed to load resource: the server responded with a status of 404 ()
css:1          Failed to load resource: the server responded with a status of 403 ()
save.js?1875:71 set force reload to 0
combatManager.js?1875:1 Combat Manager Built...
raidManager.js?1875:1 Golbin Raid Manager Built...
save.js?1875:15 Loading Save Game...
save.js?1875:15 Save Game Loaded...
main.js?1875:6 Game Loaded
cloud.js?1875:67 Connected to PlayFab successfully
MICSR.js:26 MICSR: Plotter is waiting for util
MICSR.js:26 MICSR: setting up Menu
MICSR.js:26 MICSR: Simulator is waiting for SimEnemy
MICSR.js:26 MICSR: Simulator is waiting for SimManager
MICSR.js:26 MICSR: Simulator is waiting for SimPlayer
MICSR.js:26 MICSR: setting up SimEnemy
MICSR.js:26 MICSR: setting up SimManager
MICSR.js:26 MICSR: setting up SimPlayer
MICSR.js:26 MICSR: TabCard is waiting for util
MICSR.js:26 MICSR: TabCard is waiting for Card
MICSR.js:26 MICSR: App is waiting for util
MICSR.js:26 MICSR: App is waiting for AgilityCourse
MICSR.js:26 MICSR: App is waiting for Card
MICSR.js:26 MICSR: App is waiting for CombatData
MICSR.js:26 MICSR: App is waiting for Consumables
MICSR.js:26 MICSR: App is waiting for DataExport
MICSR.js:26 MICSR: App is waiting for Import
MICSR.js:26 MICSR: App is waiting for Plotter
MICSR.js:26 MICSR: App is waiting for Loot
MICSR.js:26 MICSR: App is waiting for modifierNames
MICSR.js:26 MICSR: App is waiting for Simulator
MICSR.js:26 MICSR: App is waiting for TabCard
MICSR.js:26 MICSR: main is waiting for util
MICSR.js:26 MICSR: main is waiting for App
MICSR.js:26 MICSR: setting up util
MICSR.js:26 MICSR: setting up modifierNames
modifierNames.js:656 MICSR: no unknown modifiers detected!
modifierNames.js:656 MICSR: no non-existent modifiers detected!
MICSR.js:26 MICSR: AgilityCourse is waiting for Card
MICSR.js:26 MICSR: setting up Card
MICSR.js:26 MICSR: setting up CombatData
MICSR.js:26 MICSR: setting up Consumables
MICSR.js:26 MICSR: setting up DataExport
MICSR.js:26 MICSR: Import is waiting for Import
MICSR.js:26 MICSR: setting up Import
MICSR.js:26 MICSR: setting up Loot
utils.js?1875:128 Uncaught Error: Offline timestamp is null
    at getOfflineTimeDiff (utils.js?1875:128:7)
    at game.js?1875:76:698
getOfflineTimeDiff @ utils.js?1875:128
(anonymous) @ game.js?1875:76
MICSR.js:26 MICSR: setting up Plotter
MICSR.js:26 MICSR: setting up Simulator
MICSR.js:26 MICSR: setting up TabCard
MICSR.js:26 MICSR: setting up AgilityCourse
MICSR.js:26 MICSR: setting up Import
SEMI.js:172 Core injection good
MICSR.js:26 MICSR: setting up App
MICSR.js:26 MICSR: setting up main
css:1          Failed to load resource: the server responded with a status of 403 ()
cloud.js?1875:68 PlayFab Connected: TheSluga
utils.js:517 Game Loaded. SEMIUtils ready.
event-bus.js:57 Starting Event Bus
chrome-extension://mnjfmmpkdmgfpabgbeoclagnclmpmjgm/scripts/plugins/ore-in-bank.js:1          Failed to load resource: net::ERR_FILE_NOT_FOUND
2cloud.js?1875:75 Uncaught TypeError: Cannot read properties of undefined (reading 'Value')
    at cloud.js?1875:75:355
    at XMLHttpRequest.xhr.onloadend (PlayFabClientApi.js:101:25)
(anonymous) @ cloud.js?1875:75
xhr.onloadend @ PlayFabClientApi.js:101
menus.js:97 SEMI v0.11.1 Loaded!
cloud.js?1875:11 Synchronising with Cloud
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/sm/57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/popper.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.3

### Game Subversion

?1875

### Are you using any scripts or extensions?

Yes

**Comment by msluga13** [comment]
Found a temporary workaround but still seem to be receiving errors:

Failed to load resource: the server responded with a status of 404 ()
css:1          Failed to load resource: the server responded with a status of 403 ()
cloud.js?1875:67 Connected to PlayFab successfully
2cloud.js?1875:75 Uncaught TypeError: Cannot read properties of undefined (reading 'Value')
    at cloud.js?1875:75:355
    at XMLHttpRequest.xhr.onloadend (PlayFabClientApi.js:101:25)
save.js?1875:71 set force reload to 0
combatManager.js?1875:1 Combat Manager Built...
raidManager.js?1875:1 Golbin Raid Manager Built...
save.js?1875:15 Loading Save Game...
save.js?1875:15 Save Game Loaded...
main.js?1875:6 Game Loaded
MICSR.js:26 MICSR: setting up util
MICSR.js:26 MICSR: setting up modifierNames
modifierNames.js:656 MICSR: no unknown modifiers detected!
modifierNames.js:656 MICSR: no non-existent modifiers detected!
MICSR.js:26 MICSR: AgilityCourse is waiting for Card
MICSR.js:26 MICSR: setting up DataExport
MICSR.js:26 MICSR: setting up Plotter
2MICSR.js:26 MICSR: setting up Import
MICSR.js:26 MICSR: TabCard is waiting for Card
MICSR.js:26 MICSR: setting up Menu
MICSR.js:26 MICSR: main is waiting for App
MICSR.js:26 MICSR: setting up SimManager
MICSR.js:26 MICSR: Simulator is waiting for SimEnemy
MICSR.js:26 MICSR: Simulator is waiting for SimPlayer
MICSR.js:26 MICSR: setting up SimEnemy
MICSR.js:26 MICSR: setting up CombatData
MICSR.js:26 MICSR: setting up Card
MICSR.js:26 MICSR: setting up Loot
MICSR.js:26 MICSR: setting up Consumables
MICSR.js:26 MICSR: setting up SimPlayer
MICSR.js:26 MICSR: App is waiting for AgilityCourse
MICSR.js:26 MICSR: App is waiting for Simulator
MICSR.js:26 MICSR: App is waiting for TabCard
MICSR.js:26 MICSR: setting up AgilityCourse
MICSR.js:26 MICSR: setting up TabCard
MICSR.js:26 MICSR: setting up Simulator
MICSR.js:26 MICSR: setting up App
cloud.js?1875:67 Connected to PlayFab successfully
MICSR.js:26 MICSR: setting up main
SEMI.js:172 Core injection good
css:1          Failed to load resource: the server responded with a status of 403 ()
cloud.js?1875:11 Synchronising with Cloud
cloud.js?1875:68 PlayFab Connected: TheSluga
utils.js:517 Game Loaded. SEMIUtils ready.
event-bus.js:57 Starting Event Bus
combatManager.js?1875:1 Combat Manager Built...
MICSR.js:26 MICSR: Melvor Idle Combat Simulator Reloaded v1.6.7 loaded.
2cloud.js?1875:75 Uncaught TypeError: Cannot read properties of undefined (reading 'Value')
    at cloud.js?1875:75:355
    at XMLHttpRequest.xhr.onloadend (PlayFabClientApi.js:101:25)
chrome-extension://mnjfmmpkdmgfpabgbeoclagnclmpmjgm/scripts/plugins/ore-in-bank.js:1          Failed to load resource: net::ERR_FILE_NOT_FOUND
menus.js:97 SEMI v0.11.1 Loaded!
mastery-enhancements.js:88 Loading Mastery Enhancements
core.js:259 auto-farm enabled at 4/19/2022, 4:10:47 PM
style.css:1          Failed to load resource: the server responded with a status of 404 ()
css:1          Failed to load resource: the server responded with a status of 403 ()
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/popper.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/sm/57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
