### ISSUE TITLE
[Bug]: Unable to load save data from cloud

### ISSUE THREAD

**Issue by xealous** [MelvorIdle/melvoridle.github.io#2483]
### Describe the bug

When trying to play save data from cloud (Mobile gamesave to Browser gamesave), receiving this specific script error despite clearing cache and cookies and browser is up to date;

TypeError: Cannot read properties of undefined (reading 'classList')
    at StatsTable.setData (https://melvoridle.com/assets/js/built/statsTable.js?1978:4:28)
    at https://melvoridle.com/assets/js/built/statistics.js?1978:21:135
    at Array.forEach (<anonymous>)
    at initializeStatTables (https://melvoridle.com/assets/js/built/statistics.js?1978:21:62)
    at updateWindow (https://melvoridle.com/assets/js/game/main.js?1978:4:344)
    at finaliseLoad (https://melvoridle.com/assets/js/game/main.js?1978:376:1)
    at selectCharacter (https://melvoridle.com/assets/js/game/main.js?1978:368:228)
    at onloadEvent (https://melvoridle.com/assets/js/game/save.js?1978:80:217)
    at HTMLDivElement.onLoadCallback (https://melvoridle.com/assets/js/game/save.js?1978:85:470)
    at HTMLDivElement.<anonymous> (https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6:84821)

### Reproduction Steps

1.click 'Show Cloud Saves'
2.click on save slot (both giving error)
3.click 'confirm'

### Save Link

https://melvoridle.com/save/uYYBY6rU and https://melvoridle.com/save/SfpXXoAB

### Screenshots

![image](https://user-images.githubusercontent.com/45512020/172034466-606374a9-9dee-42b3-8357-b71dfe07fa8d.png)

### Console output

Failed to load resource: the server responded with a status of 404 (Not Found)
www.googletagmanager.com/gtag/js?id=UA-129674422-1:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
v652eace1692a40cfa3763df669d7439c1639079717194:1          Failed to load resource: the server responded with a status of 500 (Internal Server Error)
css:1          Failed to load resource: the server responded with a status of 403 (Forbidden)
v652eace1692a40cfa3763df669d7439c1639079717194:1          Failed to load resource: the server responded with a status of 500 (Internal Server Error)
v652eace1692a40cfa3763df669d7439c1639079717194:1          Failed to load resource: the server responded with a status of 500 (Internal Server Error)
cloud.js?1978:67 Connected to PlayFab successfully
cloud.js?1978:187 updatePlayerTags
cloud.js?1978:75 Error getting value of key: one_signal_token
style.css:1          Failed to load resource: the server responded with a status of 404 (Not Found)
css:1          Failed to load resource: the server responded with a status of 403 (Forbidden)
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/popper.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/sm/57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
save.js?1978:77 set force reload to 0
eventMenu.js?1978:2 Uncaught Error: Template does not exist
    at new CombatEventMenu (eventMenu.js?1978:2:7)
    at be (oneui.core.min.js:6:38922)
    at Me (oneui.core.min.js:6:47789)
    at C.fn.init.append (oneui.core.min.js:6:49610)
    at i.fn.<computed> [as append] (oneui.core.min.js:6:231098)
    at C.fn.init.<anonymous> (oneui.core.min.js:6:50700)
    at B (oneui.core.min.js:6:32199)
    at C.fn.init.html (oneui.core.min.js:6:50378)
    at Object.<anonymous> (oneui.core.min.js:6:84723)
    at r (oneui.core.min.js:6:28083)
CombatEventMenu @ eventMenu.js?1978:2
be @ oneui.core.min.js:6
Me @ oneui.core.min.js:6
append @ oneui.core.min.js:6
i.fn.<computed> @ oneui.core.min.js:6
(anonymous) @ oneui.core.min.js:6
B @ oneui.core.min.js:6
html @ oneui.core.min.js:6
(anonymous) @ oneui.core.min.js:6
r @ oneui.core.min.js:6
fireWith @ oneui.core.min.js:6
c @ oneui.core.min.js:6
(anonymous) @ oneui.core.min.js:6
load (async)
send @ oneui.core.min.js:6
ajax @ oneui.core.min.js:6
C.fn.load @ oneui.core.min.js:6
resetEntirePage @ save.js?1978:85
setForceReload @ save.js?1978:77
selectCharacter @ main.js?1978:364
(anonymous) @ main.js?1978:363
Promise.then (async)
then @ sweetalert2.min.js?1978:1
selectCharacter @ main.js?1978:363
onclick @ index_noads.php:1
utils.js?1978:149 Uncaught Error: Template does not exist
    at getTemplateElement (utils.js?1978:149:7)
    at getTemplateNode (utils.js?1978:150:60)
    at new MultiProgressBar (agilityMenus.js?1978:40:283)
    at be (oneui.core.min.js:6:38922)
    at Me (oneui.core.min.js:6:47789)
    at C.fn.init.append (oneui.core.min.js:6:49610)
    at i.fn.<computed> [as append] (oneui.core.min.js:6:231098)
    at C.fn.init.<anonymous> (oneui.core.min.js:6:50700)
    at B (oneui.core.min.js:6:32199)
    at C.fn.init.html (oneui.core.min.js:6:50378)
getTemplateElement @ utils.js?1978:149
getTemplateNode @ utils.js?1978:150
MultiProgressBar @ agilityMenus.js?1978:40
be @ oneui.core.min.js:6
Me @ oneui.core.min.js:6
append @ oneui.core.min.js:6
i.fn.<computed> @ oneui.core.min.js:6
(anonymous) @ oneui.core.min.js:6
B @ oneui.core.min.js:6
html @ oneui.core.min.js:6
(anonymous) @ oneui.core.min.js:6
r @ oneui.core.min.js:6
fireWith @ oneui.core.min.js:6
c @ oneui.core.min.js:6
(anonymous) @ oneui.core.min.js:6
load (async)
send @ oneui.core.min.js:6
ajax @ oneui.core.min.js:6
C.fn.load @ oneui.core.min.js:6
resetEntirePage @ save.js?1978:85
setForceReload @ save.js?1978:77
selectCharacter @ main.js?1978:364
(anonymous) @ main.js?1978:363
Promise.then (async)
then @ sweetalert2.min.js?1978:1
selectCharacter @ main.js?1978:363
onclick @ index_noads.php:1
utils.js?1978:149 Uncaught Error: Template does not exist
    at getTemplateElement (utils.js?1978:149:7)
    at getTemplateNode (utils.js?1978:150:60)
    at new AltMagicMenu (altMagicMenu.js?1978:1:133)
    at be (oneui.core.min.js:6:38922)
    at Me (oneui.core.min.js:6:47789)
    at C.fn.init.append (oneui.core.min.js:6:49610)
    at i.fn.<computed> [as append] (oneui.core.min.js:6:231098)
    at C.fn.init.<anonymous> (oneui.core.min.js:6:50700)
    at B (oneui.core.min.js:6:32199)
    at C.fn.init.html (oneui.core.min.js:6:50378)
getTemplateElement @ utils.js?1978:149
getTemplateNode @ utils.js?1978:150
AltMagicMenu @ altMagicMenu.js?1978:1
be @ oneui.core.min.js:6
Me @ oneui.core.min.js:6
append @ oneui.core.min.js:6
i.fn.<computed> @ oneui.core.min.js:6
(anonymous) @ oneui.core.min.js:6
B @ oneui.core.min.js:6
html @ oneui.core.min.js:6
(anonymous) @ oneui.core.min.js:6
r @ oneui.core.min.js:6
fireWith @ oneui.core.min.js:6
c @ oneui.core.min.js:6
(anonymous) @ oneui.core.min.js:6
load (async)
send @ oneui.core.min.js:6
ajax @ oneui.core.min.js:6
C.fn.load @ oneui.core.min.js:6
resetEntirePage @ save.js?1978:85
setForceReload @ save.js?1978:77
selectCharacter @ main.js?1978:364
(anonymous) @ main.js?1978:363
Promise.then (async)
then @ sweetalert2.min.js?1978:1
selectCharacter @ main.js?1978:363
onclick @ index_noads.php:1
utils.js?1978:149 Uncaught Error: Template does not exist
    at getTemplateElement (utils.js?1978:149:7)
    at getTemplateNode (utils.js?1978:150:60)
    at new AltMagicItemMenu (altMagicMenu.js?1978:19:184)
    at be (oneui.core.min.js:6:38922)
    at Me (oneui.core.min.js:6:47789)
    at C.fn.init.append (oneui.core.min.js:6:49610)
    at i.fn.<computed> [as append] (oneui.core.min.js:6:231098)
    at C.fn.init.<anonymous> (oneui.core.min.js:6:50700)
    at B (oneui.core.min.js:6:32199)
    at C.fn.init.html (oneui.core.min.js:6:50378)
getTemplateElement @ utils.js?1978:149
getTemplateNode @ utils.js?1978:150
AltMagicItemMenu @ altMagicMenu.js?1978:19
be @ oneui.core.min.js:6
Me @ oneui.core.min.js:6
append @ oneui.core.min.js:6
i.fn.<computed> @ oneui.core.min.js:6
(anonymous) @ oneui.core.min.js:6
B @ oneui.core.min.js:6
html @ oneui.core.min.js:6
(anonymous) @ oneui.core.min.js:6
r @ oneui.core.min.js:6
fireWith @ oneui.core.min.js:6
c @ oneui.core.min.js:6
(anonymous) @ oneui.core.min.js:6
load (async)
send @ oneui.core.min.js:6
ajax @ oneui.core.min.js:6
C.fn.load @ oneui.core.min.js:6
resetEntirePage @ save.js?1978:85
setForceReload @ save.js?1978:77
selectCharacter @ main.js?1978:364
(anonymous) @ main.js?1978:363
Promise.then (async)
then @ sweetalert2.min.js?1978:1
selectCharacter @ main.js?1978:363
onclick @ index_noads.php:1
utils.js?1978:149 Uncaught Error: Template does not exist
    at getTemplateElement (utils.js?1978:149:7)
    at getTemplateNode (utils.js?1978:150:60)
    at new AstrologyInformationPanel (astrologyMenus.js?1978:33:219)
    at be (oneui.core.min.js:6:38922)
    at Me (oneui.core.min.js:6:47789)
    at C.fn.init.append (oneui.core.min.js:6:49610)
    at i.fn.<computed> [as append] (oneui.core.min.js:6:231098)
    at C.fn.init.<anonymous> (oneui.core.min.js:6:50700)
    at B (oneui.core.min.js:6:32199)
    at C.fn.init.html (oneui.core.min.js:6:50378)
getTemplateElement @ utils.js?1978:149
getTemplateNode @ utils.js?1978:150
AstrologyInformationPanel @ astrologyMenus.js?1978:33
be @ oneui.core.min.js:6
Me @ oneui.core.min.js:6
append @ oneui.core.min.js:6
i.fn.<computed> @ oneui.core.min.js:6
(anonymous) @ oneui.core.min.js:6
B @ oneui.core.min.js:6
html @ oneui.core.min.js:6
(anonymous) @ oneui.core.min.js:6
r @ oneui.core.min.js:6
fireWith @ oneui.core.min.js:6
c @ oneui.core.min.js:6
(anonymous) @ oneui.core.min.js:6
load (async)
send @ oneui.core.min.js:6
ajax @ oneui.core.min.js:6
C.fn.load @ oneui.core.min.js:6
resetEntirePage @ save.js?1978:85
setForceReload @ save.js?1978:77
selectCharacter @ main.js?1978:364
(anonymous) @ main.js?1978:363
Promise.then (async)
then @ sweetalert2.min.js?1978:1
selectCharacter @ main.js?1978:363
onclick @ index_noads.php:1
utils.js?1978:149 Uncaught Error: Template does not exist
    at getTemplateElement (utils.js?1978:149:7)
    at getTemplateNode (utils.js?1978:150:60)
    at new AstrologyExplorationPanel (astrologyMenus.js?1978:18:267)
    at be (oneui.core.min.js:6:38922)
    at Me (oneui.core.min.js:6:47789)
    at C.fn.init.append (oneui.core.min.js:6:49610)
    at i.fn.<computed> [as append] (oneui.core.min.js:6:231098)
    at C.fn.init.<anonymous> (oneui.core.min.js:6:50700)
    at B (oneui.core.min.js:6:32199)
    at C.fn.init.html (oneui.core.min.js:6:50378)
getTemplateElement @ utils.js?1978:149
getTemplateNode @ utils.js?1978:150
AstrologyExplorationPanel @ astrologyMenus.js?1978:18
be @ oneui.core.min.js:6
Me @ oneui.core.min.js:6
append @ oneui.core.min.js:6
i.fn.<computed> @ oneui.core.min.js:6
(anonymous) @ oneui.core.min.js:6
B @ oneui.core.min.js:6
html @ oneui.core.min.js:6
(anonymous) @ oneui.core.min.js:6
r @ oneui.core.min.js:6
fireWith @ oneui.core.min.js:6
c @ oneui.core.min.js:6
(anonymous) @ oneui.core.min.js:6
load (async)
send @ oneui.core.min.js:6
ajax @ oneui.core.min.js:6
C.fn.load @ oneui.core.min.js:6
resetEntirePage @ save.js?1978:85
setForceReload @ save.js?1978:77
selectCharacter @ main.js?1978:364
(anonymous) @ main.js?1978:363
Promise.then (async)
then @ sweetalert2.min.js?1978:1
selectCharacter @ main.js?1978:363
onclick @ index_noads.php:1
25utils.js?1978:149 Uncaught Error: Template does not exist
    at getTemplateElement (utils.js?1978:149:7)
    at getTemplateNode (utils.js?1978:150:60)
    at new StatsTable (statsTable.js?1978:1:238)
    at be (oneui.core.min.js:6:38922)
    at Me (oneui.core.min.js:6:47789)
    at C.fn.init.append (oneui.core.min.js:6:49610)
    at i.fn.<computed> [as append] (oneui.core.min.js:6:231098)
    at C.fn.init.<anonymous> (oneui.core.min.js:6:50700)
    at B (oneui.core.min.js:6:32199)
    at C.fn.init.html (oneui.core.min.js:6:50378)
getTemplateElement @ utils.js?1978:149
getTemplateNode @ utils.js?1978:150
StatsTable @ statsTable.js?1978:1
be @ oneui.core.min.js:6
Me @ oneui.core.min.js:6
append @ oneui.core.min.js:6
i.fn.<computed> @ oneui.core.min.js:6
(anonymous) @ oneui.core.min.js:6
B @ oneui.core.min.js:6
html @ oneui.core.min.js:6
(anonymous) @ oneui.core.min.js:6
r @ oneui.core.min.js:6
fireWith @ oneui.core.min.js:6
c @ oneui.core.min.js:6
(anonymous) @ oneui.core.min.js:6
load (async)
send @ oneui.core.min.js:6
ajax @ oneui.core.min.js:6
C.fn.load @ oneui.core.min.js:6
resetEntirePage @ save.js?1978:85
setForceReload @ save.js?1978:77
selectCharacter @ main.js?1978:364
(anonymous) @ main.js?1978:363
Promise.then (async)
then @ sweetalert2.min.js?1978:1
selectCharacter @ main.js?1978:363
onclick @ index_noads.php:1
combatManager.js?1978:1 Combat Manager Built...
raidManager.js?1978:1 Golbin Raid Manager Built...
save.js?1978:20 Loading Save Game...
save.js?1978:20 Save Game Loaded...
main.js?1978:9 TypeError: Cannot read properties of undefined (reading 'classList')
    at StatsTable.setData (statsTable.js?1978:4:28)
    at statistics.js?1978:21:135
    at Array.forEach (<anonymous>)
    at initializeStatTables (statistics.js?1978:21:62)
    at updateWindow (main.js?1978:4:344)
    at finaliseLoad (main.js?1978:376:1)
    at selectCharacter (main.js?1978:364:221)
    at onloadEvent (save.js?1978:80:217)
    at HTMLDivElement.onLoadCallback (save.js?1978:85:470)
    at HTMLDivElement.<anonymous> (oneui.core.min.js:6:84821)
index.html:549          GET https://static.cloudflareinsights.com/beacon.min.js/v652eace1692a40cfa3763df669d7439c1639079717194 net::ERR_ABORTED 500 (Internal Server Error)
MelvorIdleFanartCompH1TermsClean22022022_2_.d.html:701          GET https://static.cloudflareinsights.com/beacon.min.js/v652eace1692a40cfa3763df669d7439c1639079717194 net::ERR_ABORTED 500 (Internal Server Error)
MelvorIdleFanartCompH1TermsClean22022022_2_.d.html:491          GET https://themes.googleusercontent.com/fonts/css?kit=fpjTOVmNbO4Lz34iLyptLTi9jKYd1gJzj5O2gWsEpXoyck2WCYPEMNySjZN0CHed_kmCvy597kDopqFAXvpeaA 403 (Forbidden)

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.4

### Game Subversion

no subversion located (searched in elements too)

### Are you using any scripts or extensions?

Yes (adblocker)

**Comment by MelvorIdle** [comment]
Due to the latest v1.1 major update and rewrite to the game on 18 October 2022, this issue will be closed.

In the event this issue is still occurring, please open a new issue so we can address it.
