### ISSUE TITLE
[Bug]: Can't Open the game 

### ISSUE THREAD

**Issue by gvnvdssr** [MelvorIdle/melvoridle.github.io#2491]
### Describe the bug

I was first found this game through searching by google on current best idle game. At first it direct me to the game through https://melvoridle.com/index_ads.php# (v1.0.4), i create a free account and i try to play it on chrome and firefox and it does well.
As I progress, i decided to enjoy it more by purchasing on steam. 

But when I open the game through steam it says "The webpage at https://steam.melvoridle.com/ might be temporarily down or it may have moved permanently to a new web address." 
![MELVORIDLE_STEAM_LOGIN_000](https://user-images.githubusercontent.com/61072998/173209020-368786cc-a2a1-4139-badc-7146feb122b2.png)

So I try to open the https://steam.melvoridle.com/ direct on firefox and then chrome, I log in with the same free account that was created before. But when it load the saved slot, it says 

Firefox Version 101.0.1 (64-bit):
```
initSteam@https://steam.melvoridle.com/assets/js/game/main.js?1983:398:78
updateWindow@https://steam.melvoridle.com/assets/js/game/main.js?1983:6:149
finaliseLoad@https://steam.melvoridle.com/assets/js/game/main.js?1983:376:1
selectCharacter@https://steam.melvoridle.com/assets/js/game/main.js?1983:368:228
onloadEvent@https://steam.melvoridle.com/assets/js/game/save.js?1983:82:232
onLoadCallback@https://steam.melvoridle.com/assets/js/game/save.js?1983:87:481
C.fn.load/</<@https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6:84821
each@https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6:2967
each@https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6:1453
C.fn.load/<@https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6:84803
r@https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6:28083
fireWith@https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6:28851
c@https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6:79484
send/o/<@https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6:81937
```

Chrome Version 102.0.5005.115 (Official Build) (64-bit):
```
TypeError: Cannot read properties of undefined (reading 'initAPI')
    at initSteam (https://steam.melvoridle.com/assets/js/game/main.js?1983:398:96)
    at updateWindow (https://steam.melvoridle.com/assets/js/game/main.js?1983:6:149)
    at finaliseLoad (https://steam.melvoridle.com/assets/js/game/main.js?1983:376:1)
    at selectCharacter (https://steam.melvoridle.com/assets/js/game/main.js?1983:368:228)
    at onloadEvent (https://steam.melvoridle.com/assets/js/game/save.js?1983:82:217)
    at HTMLDivElement.onLoadCallback (https://steam.melvoridle.com/assets/js/game/save.js?1983:87:470)
    at HTMLDivElement.<anonymous> (https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6:84821)
    at Function.each (https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6:2967)
    at C.fn.init.each (https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6:1453)
    at Object.<anonymous> (https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6:84803)
```

![MELVORIDLE_CHROME_LOGIN_000](https://user-images.githubusercontent.com/61072998/173209174-07881490-cd23-433e-8b07-dacc8ca6529a.png)

As it says try to clear the cache, i cleared both my browser cache but it still give me same pop out.

Is there something I miss? or should I do something first?
Please guide me through this..

### Reproduction Steps

1. Open Melvor Idle Through Steam
2. "The webpage at https://steam.melvoridle.com/ might be temporarily down or it may have moved permanently to a new web address." pop up

1. Open Melvor Idle Through Chrome / Firefox
2. LogIn
3. Select Character / Slot
4. Error Message pop-up

### Expected behaviour

Login / Game Load Success

### Save Link

https://melvoridle.com/save/y3BDnywj

### Screenshots

![MELVORIDLE_STEAM_LOGIN_000](https://user-images.githubusercontent.com/61072998/173209020-368786cc-a2a1-4139-badc-7146feb122b2.png)

![MELVORIDLE_CHROME_LOGIN_000](https://user-images.githubusercontent.com/61072998/173209174-07881490-cd23-433e-8b07-dacc8ca6529a.png)

### Console output

Firefox Version 101.0.1 (64-bit):
```
initSteam@https://steam.melvoridle.com/assets/js/game/main.js?1983:398:78
updateWindow@https://steam.melvoridle.com/assets/js/game/main.js?1983:6:149
finaliseLoad@https://steam.melvoridle.com/assets/js/game/main.js?1983:376:1
selectCharacter@https://steam.melvoridle.com/assets/js/game/main.js?1983:368:228
onloadEvent@https://steam.melvoridle.com/assets/js/game/save.js?1983:82:232
onLoadCallback@https://steam.melvoridle.com/assets/js/game/save.js?1983:87:481
C.fn.load/</<@https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6:84821
each@https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6:2967
each@https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6:1453
C.fn.load/<@https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6:84803
r@https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6:28083
fireWith@https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6:28851
c@https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6:79484
send/o/<@https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6:81937
```

Chrome Version 102.0.5005.115 (Official Build) (64-bit):
```
TypeError: Cannot read properties of undefined (reading 'initAPI')
    at initSteam (https://steam.melvoridle.com/assets/js/game/main.js?1983:398:96)
    at updateWindow (https://steam.melvoridle.com/assets/js/game/main.js?1983:6:149)
    at finaliseLoad (https://steam.melvoridle.com/assets/js/game/main.js?1983:376:1)
    at selectCharacter (https://steam.melvoridle.com/assets/js/game/main.js?1983:368:228)
    at onloadEvent (https://steam.melvoridle.com/assets/js/game/save.js?1983:82:217)
    at HTMLDivElement.onLoadCallback (https://steam.melvoridle.com/assets/js/game/save.js?1983:87:470)
    at HTMLDivElement.<anonymous> (https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6:84821)
    at Function.each (https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6:2967)
    at C.fn.init.each (https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6:1453)
    at Object.<anonymous> (https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6:84803)
```

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [X] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.4

### Game Subversion

?1983

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
steam.melvoridle.com cannot be accessed via the browser due to the requirement of Steam needing to be running to load the game.

Did this issue automatically resolve itself on Steam?

**Comment by coolrox95** [comment]
Closing as no response to the question was provided.
