### ISSUE TITLE
[Bug]: game failing to load

### ISSUE THREAD

**Issue by GiantHandBanana** [MelvorIdle/melvoridle.github.io#2551]
### Describe the bug

Getting an "oh dear... it looks like the game failed to load" message when trying to log in. 

The error text below is:
TypeError: Cannot read properties of undefined (reading 'classList')
    at StatsTable.setData (https://melvoridle.com/assets/js/built/statsTable.js?2077:4:28)
    at https://melvoridle.com/assets/js/built/statistics.js?2077:21:135
    at Array.forEach (<anonymous>)
    at initializeStatTables (https://melvoridle.com/assets/js/built/statistics.js?2077:21:62)
    at updateWindow (https://melvoridle.com/assets/js/game/main.js?2077:4:510)
    at finaliseLoad (https://melvoridle.com/assets/js/game/main.js?2077:395:1)
    at selectCharacter (https://melvoridle.com/assets/js/game/main.js?2077:383:221)
    at onloadEvent (https://melvoridle.com/assets/js/game/save.js?2077:82:217)
    at HTMLDivElement.onLoadCallback (https://melvoridle.com/assets/js/game/save.js?2077:87:470)
    at HTMLDivElement.<anonymous> (https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6:84821)

I was getting an Authentication Error yesterday during the day and could not update my cloud save, so I tried to refresh and sign back in when I started getting the bug. I also tried loading my last cloud save instead of my local save, and it looks like my local save was overwritten but I'm still getting the same error. 

I do also have a second character that does not seem to be having this issue. Primary character is regular mode, secondary is adventure mode, if that makes a difference.

### Reproduction Steps

1. Go to Login page
2. Click on account in Save Slot #1

(sorry, this is probably specific to just me, and I'm not sure how to reproduce the initial bug)

### Expected behaviour

Expected to be able to log in.

### Save Link

https://melvoridle.com/save/KoRC9v9A

### Screenshots

![image](https://user-images.githubusercontent.com/110542536/182613699-ebcda3dc-8ed0-41fe-a389-142e0b865a7c.png)

### Console output

style.css:1          Failed to load resource: the server responded with a status of 404 (Not Found)
v652eace1692a40cfa3763df669d7439c1639079717194:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
v652eace1692a40cfa3763df669d7439c1639079717194:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
v652eace1692a40cfa3763df669d7439c1639079717194:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
CopyofMelvorIdleMemeContestTCsv3.docx.html:524 Refused to apply style from 'https://themes.googleusercontent.com/fonts/css?kit=fpjTOVmNbO4Lz34iLyptLTi9jKYd1gJzj5O2gWsEpXoyck2WCYPEMNySjZN0CHed_kmCvy597kDopqFAXvpeaA' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
v652eace1692a40cfa3763df669d7439c1639079717194:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
page.js:13 M-Files For chrome is supported.
cloud.js?2077:67 Connected to PlayFab successfully
cloud.js?2077:75 Error getting value of key: one_signal_token
save.js?2077:42 Copied to clipboard successfully.
save.js?2077:79 set force reload to 0
eventMenu.js?2077:2 Uncaught Error: Template does not exist
    at new CombatEventMenu (eventMenu.js?2077:2:7)
    at be (oneui.core.min.js:6:38922)
    at Me (oneui.core.min.js:6:47789)
    at C.fn.init.append (oneui.core.min.js:6:49610)
    at i.fn.<computed> [as append] (oneui.core.min.js:6:231098)
    at C.fn.init.<anonymous> (oneui.core.min.js:6:50700)
    at B (oneui.core.min.js:6:32199)
    at C.fn.init.html (oneui.core.min.js:6:50378)
    at Object.<anonymous> (oneui.core.min.js:6:84723)
    at r (oneui.core.min.js:6:28083)
utils.js?2077:149 Uncaught Error: Template does not exist
    at getTemplateElement (utils.js?2077:149:7)
    at getTemplateNode (utils.js?2077:150:60)
    at new MultiProgressBar (agilityMenus.js?2077:40:283)
    at be (oneui.core.min.js:6:38922)
    at Me (oneui.core.min.js:6:47789)
    at C.fn.init.append (oneui.core.min.js:6:49610)
    at i.fn.<computed> [as append] (oneui.core.min.js:6:231098)
    at C.fn.init.<anonymous> (oneui.core.min.js:6:50700)
    at B (oneui.core.min.js:6:32199)
    at C.fn.init.html (oneui.core.min.js:6:50378)
utils.js?2077:149 Uncaught Error: Template does not exist
    at getTemplateElement (utils.js?2077:149:7)
    at getTemplateNode (utils.js?2077:150:60)
    at new AltMagicMenu (altMagicMenu.js?2077:1:133)
    at be (oneui.core.min.js:6:38922)
    at Me (oneui.core.min.js:6:47789)
    at C.fn.init.append (oneui.core.min.js:6:49610)
    at i.fn.<computed> [as append] (oneui.core.min.js:6:231098)
    at C.fn.init.<anonymous> (oneui.core.min.js:6:50700)
    at B (oneui.core.min.js:6:32199)
    at C.fn.init.html (oneui.core.min.js:6:50378)
utils.js?2077:149 Uncaught Error: Template does not exist
    at getTemplateElement (utils.js?2077:149:7)
    at getTemplateNode (utils.js?2077:150:60)
    at new AltMagicItemMenu (altMagicMenu.js?2077:19:184)
    at be (oneui.core.min.js:6:38922)
    at Me (oneui.core.min.js:6:47789)
    at C.fn.init.append (oneui.core.min.js:6:49610)
    at i.fn.<computed> [as append] (oneui.core.min.js:6:231098)
    at C.fn.init.<anonymous> (oneui.core.min.js:6:50700)
    at B (oneui.core.min.js:6:32199)
    at C.fn.init.html (oneui.core.min.js:6:50378)
utils.js?2077:149 Uncaught Error: Template does not exist
    at getTemplateElement (utils.js?2077:149:7)
    at getTemplateNode (utils.js?2077:150:60)
    at new AstrologyInformationPanel (astrologyMenus.js?2077:33:219)
    at be (oneui.core.min.js:6:38922)
    at Me (oneui.core.min.js:6:47789)
    at C.fn.init.append (oneui.core.min.js:6:49610)
    at i.fn.<computed> [as append] (oneui.core.min.js:6:231098)
    at C.fn.init.<anonymous> (oneui.core.min.js:6:50700)
    at B (oneui.core.min.js:6:32199)
    at C.fn.init.html (oneui.core.min.js:6:50378)
utils.js?2077:149 Uncaught Error: Template does not exist
    at getTemplateElement (utils.js?2077:149:7)
    at getTemplateNode (utils.js?2077:150:60)
    at new AstrologyExplorationPanel (astrologyMenus.js?2077:18:267)
    at be (oneui.core.min.js:6:38922)
    at Me (oneui.core.min.js:6:47789)
    at C.fn.init.append (oneui.core.min.js:6:49610)
    at i.fn.<computed> [as append] (oneui.core.min.js:6:231098)
    at C.fn.init.<anonymous> (oneui.core.min.js:6:50700)
    at B (oneui.core.min.js:6:32199)
    at C.fn.init.html (oneui.core.min.js:6:50378)
25utils.js?2077:149 Uncaught Error: Template does not exist
    at getTemplateElement (utils.js?2077:149:7)
    at getTemplateNode (utils.js?2077:150:60)
    at new StatsTable (statsTable.js?2077:1:238)
    at be (oneui.core.min.js:6:38922)
    at Me (oneui.core.min.js:6:47789)
    at C.fn.init.append (oneui.core.min.js:6:49610)
    at i.fn.<computed> [as append] (oneui.core.min.js:6:231098)
    at C.fn.init.<anonymous> (oneui.core.min.js:6:50700)
    at B (oneui.core.min.js:6:32199)
    at C.fn.init.html (oneui.core.min.js:6:50378)
combatManager.js?2077:1 Combat Manager Built...
raidManager.js?2077:1 Golbin Raid Manager Built...
save.js?2077:20 Loading Save Game...
save.js?2077:20 Save Game Loaded...
main.js?2077:7 TypeError: Cannot read properties of undefined (reading 'classList')
    at StatsTable.setData (statsTable.js?2077:4:28)
    at statistics.js?2077:21:135
    at Array.forEach (<anonymous>)
    at initializeStatTables (statistics.js?2077:21:62)
    at updateWindow (main.js?2077:4:510)
    at finaliseLoad (main.js?2077:395:1)
    at selectCharacter (main.js?2077:383:221)
    at onloadEvent (save.js?2077:82:217)
    at HTMLDivElement.onLoadCallback (save.js?2077:87:470)
    at HTMLDivElement.<anonymous> (oneui.core.min.js:6:84821)
v652eace1692a40cfa3763df669d7439c1639079717194:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
firemaking%20agility.svg:1          Failed to load resource: the server responded with a status of 403 (Forbidden)
v652eace1692a40cfa3763df669d7439c1639079717194:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
v652eace1692a40cfa3763df669d7439c1639079717194:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
CopyofMelvorIdleMemeContestTCsv3.docx.html:646 Refused to apply style from 'https://themes.googleusercontent.com/fonts/css?kit=fpjTOVmNbO4Lz34iLyptLTi9jKYd1gJzj5O2gWsEpXoyck2WCYPEMNySjZN0CHed_kmCvy597kDopqFAXvpeaA' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
style.css:1          Failed to load resource: the server responded with a status of 404 (Not Found)
CopyofMelvorIdleMemeContestTCsv3.docx.html:1 Refused to apply style from 'https://themes.googleusercontent.com/fonts/css?kit=fpjTOVmNbO4Lz34iLyptLTi9jKYd1gJzj5O2gWsEpXoyck2WCYPEMNySjZN0CHed_kmCvy597kDopqFAXvpeaA' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
DevTools failed to load source map: Could not load content for chrome-extension://aoiidodopnnhiflaflbfeblnojefhigh/purify.min.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/core/v018/assets/js/popper.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.melvor.net/sm/57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0.5

### Game Subversion

Can't verify but I think I was on 2077

### Are you using any scripts or extensions?

Yes

**Comment by GiantHandBanana** [comment]
Three updates:
- This is now happening with my adventure mode character too. This morning, I refreshed to check and was able to log back in. Just refreshed again and now I'm getting this error when opening it:

setData@https://melvoridle.com/assets/js/built/statsTable.js?2077:4:15
initializeStatTables/<@https://melvoridle.com/assets/js/built/statistics.js?2077:21:135
initializeStatTables@https://melvoridle.com/assets/js/built/statistics.js?2077:21:62
updateWindow@https://melvoridle.com/assets/js/game/main.js?2077:4:510
finaliseLoad@https://melvoridle.com/assets/js/game/main.js?2077:395:1
selectCharacter@https://melvoridle.com/assets/js/game/main.js?2077:387:228
onloadEvent@https://melvoridle.com/assets/js/game/save.js?2077:82:232
onLoadCallback@https://melvoridle.com/assets/js/game/save.js?2077:87:481
C.fn.load/</<@https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6:84821
each@https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6:2967
each@https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6:1453
C.fn.load/<@https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6:84803
r@https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6:28083
fireWith@https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6:28851
c@https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6:79484
send/o/<@https://cdn.melvor.net/core/v018/assets/js/oneui.core.min.js:6:81937

- I disabled all extensions in Chrome and tried in Firefox, getting the same error.
- I downloaded my Adventure Mode save earlier today when it was working (after refreshing and logging back in) and just tried to import it to a new slot, same error.
