### ISSUE TITLE
[Bug]: Firemaking - Linden Logs don't appear in 'Select your Log' drop down

### ISSUE THREAD

**Issue by NephilimWraith** [MelvorIdle/melvoridle.github.io#2882]
### Describe the bug

![Linden Logs Missing](https://user-images.githubusercontent.com/117191201/199268018-1b520a33-91c8-4b80-ac4c-cb75100699da.PNG)

### Reproduction Steps

1. Go to Firemaking
2. Click Select a log Dropdown
3. scroll to bottom
4. Don't find Linden Logs

### Expected behaviour

I believe Linden Logs should be in the list to burn. 

### Save Link

https://melvoridle.com/save/7ElKMGP7

### Console output

DevTools failed to load source map: Could not load content for chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/browser-polyfill.js.map: System error: net::ERR_FILE_NOT_FOUND
index_game.php:52          GET https://melvoridle.com/style.css?2 net::ERR_ABORTED 404
DevTools failed to load source map: Could not load content for https://melvoridle.com/sm/57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://melvoridle.com/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/browser-polyfill.js.map: System error: net::ERR_FILE_NOT_FOUND
DevTools failed to load source map: Could not load content for https://melvoridle.com/assets/js/popper.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/browser-polyfill.js.map: System error: net::ERR_FILE_NOT_FOUND
cloudManager.js?4645:197 Silent Sign in with JWT
cloudManager.js?4645:197 Validating Melvor Cloud token
cloudManager.js?4645:197 Storing Melvor Cloud Token
cloudManager.js?4645:197 Initializing PlayFab login. Method: customID
cloudManager.js?4645:197 Logging in with Custom ID via PlayFab
cloudManager.js?4645:197 Login with custom ID success
cloudManager.js?4645:197 Getting account info
cloudManager.js?4645:197 Account info retrieved
cloudManager.js?4645:197 Authenticated w/ Melvor Cloud: true
cloudManager.js?4645:197 Authenticated w/ PlayFab: true
cloudManager.js?4645:197 Checking for valid full version
cloudManager.js?4645:197 Checking for valid TotH purchase
cloudManager.js?4645:197 Loading Game Data...
save.js?4645:111 Registered Demo Data.
save.js?4645:111 Registered Full Version Data.
save.js?4645:111 Registered Throne of the Herald Data.
cloudManager.js?4645:197 Initializing Mod Manager...
cloud.js?4645:147 PlayFab Data Stored successfully.
cloudManager.js?4645:197 Checking for Mod Updates...
cloudManager.js?4645:197 Loading Mods...
cloudManager.js?4645:197 Loading Mods (1/1): Mastery Pool Can Overflow (v1.2.0)
cloudManager.js?4645:197 Loading Local Saves...
cloudManager.js?4645:197 Loading Cloud Saves...
cloudManager.js?4645:197 Getting saves from playfab
cloudManager.js?4645:197 Saves retrieved
characterSelect.js?4645:5 Loading character selection
cloudManager.js?4645:292 Connected to PlayFab successfully
main.js?4645:15 Game Loaded
Card.js:605 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (Card.js:605:35)
    at Card.js:630:30
waitLoadOrder @ Card.js:605
(anonymous) @ Card.js:630
CombatData.js:174 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (CombatData.js:174:35)
    at CombatData.js:199:30
waitLoadOrder @ CombatData.js:174
(anonymous) @ CombatData.js:199
Consumables.js:397 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (Consumables.js:397:35)
    at Consumables.js:422:30
waitLoadOrder @ Consumables.js:397
(anonymous) @ Consumables.js:422
DataExport.js:186 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (DataExport.js:186:35)
    at DataExport.js:211:30
waitLoadOrder @ DataExport.js:186
(anonymous) @ DataExport.js:211
ExportCheat.js:192 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (ExportCheat.js:192:35)
    at ExportCheat.js:217:30
waitLoadOrder @ ExportCheat.js:192
(anonymous) @ ExportCheat.js:217
Import.js:476 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (Import.js:476:35)
    at Import.js:501:30
waitLoadOrder @ Import.js:476
(anonymous) @ Import.js:501
Loot.js:585 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (Loot.js:585:35)
    at Loot.js:610:30
waitLoadOrder @ Loot.js:585
(anonymous) @ Loot.js:610
Plotter.js:545 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (Plotter.js:545:35)
    at Plotter.js:570:30
waitLoadOrder @ Plotter.js:545
(anonymous) @ Plotter.js:570
Menu.js:168 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (Menu.js:168:35)
    at Menu.js:193:30
waitLoadOrder @ Menu.js:168
(anonymous) @ Menu.js:193
Simulator.js:1173 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (Simulator.js:1173:35)
    at Simulator.js:1198:30
waitLoadOrder @ Simulator.js:1173
(anonymous) @ Simulator.js:1198
SimEnemy.js:75 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (SimEnemy.js:75:35)
    at SimEnemy.js:100:30
waitLoadOrder @ SimEnemy.js:75
(anonymous) @ SimEnemy.js:100
SimManager.js:330 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (SimManager.js:330:35)
    at SimManager.js:355:30
waitLoadOrder @ SimManager.js:330
(anonymous) @ SimManager.js:355
SimPlayer.js:807 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (SimPlayer.js:807:35)
    at SimPlayer.js:832:30
waitLoadOrder @ SimPlayer.js:807
(anonymous) @ SimPlayer.js:832
TabCard.js:131 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (TabCard.js:131:35)
    at TabCard.js:156:30
waitLoadOrder @ TabCard.js:131
(anonymous) @ TabCard.js:156
App.js:3018 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (App.js:3018:35)
    at App.js:3043:30
waitLoadOrder @ App.js:3018
(anonymous) @ App.js:3043
main.js:99 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (main.js:99:35)
    at main.js:124:30
waitLoadOrder @ main.js:99
(anonymous) @ main.js:124
util.js:251 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (util.js:251:35)
    at util.js:276:30
waitLoadOrder @ util.js:251
(anonymous) @ util.js:276
modifierNames.js:931 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (modifierNames.js:931:35)
    at modifierNames.js:956:30
waitLoadOrder @ modifierNames.js:931
(anonymous) @ modifierNames.js:956
AgilityCourse.js:255 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (AgilityCourse.js:255:35)
    at AgilityCourse.js:280:30
waitLoadOrder @ AgilityCourse.js:255
(anonymous) @ AgilityCourse.js:280
DevTools failed to load source map: Could not load content for chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/browser-polyfill.js.map: System error: net::ERR_FILE_NOT_FOUND
cloud.js?4645:29 Synchronising with Cloud

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4645

### Are you using any mods?

Yes

**Comment by NephilimWraith** [comment]
I didn't have any Linden Logs in my inventory. 
Closing issue.
