### ISSUE TITLE
[Bug]: Gave all my stardust back but didn't reset any astrology perks

### ISSUE THREAD

**Issue by pelletier2017** [MelvorIdle/melvoridle.github.io#2894]
### Describe the bug

On login while thieving offline, I received a drop for all my stardust and golden stardust for a total of about 25k of each. When this happened, I had opened the app on mobile and it asked me to login when it normally stays logged in. I had already received the astrology reset from a while ago so I had spent my stardust on the new perks. All the perks were not reset after receiving this new large stardust drop. After cloud saving on mobile, the stardust did transfer to my save on the web browser.

### Reproduction Steps

N/A unknown how to reproduce

### Expected behaviour

Not receiving a second reset of stardust/golden stardust especially not when the perks were not reset.

### Save Link

https://melvoridle.com/save/YY4D17ZI

### Screenshots

![astrologyBug](https://user-images.githubusercontent.com/20457910/199497104-1f7a4663-13f7-4073-a960-78aa4440114f.png)

### Console output

style.css:1          Failed to load resource: the server responded with a status of 404 ()
vaafb692b2aea4879b33c060e79fe94621666317369993:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
vaafb692b2aea4879b33c060e79fe94621666317369993:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
vaafb692b2aea4879b33c060e79fe94621666317369993:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
Plotter.js:556 Plotter is waiting for the MICSR object
Loot.js:596 Loot is waiting for the MICSR object
Menu.js:179 Menu is waiting for the MICSR object
Simulator.js:1184 Simulator is waiting for the MICSR object
SimEnemy.js:86 SimEnemy is waiting for the MICSR object
SimManager.js:341 SimManager is waiting for the MICSR object
SimPlayer.js:818 SimPlayer is waiting for the MICSR object
TabCard.js:142 TabCard is waiting for the MICSR object
App.js:3029 App is waiting for the MICSR object
main.js:110 main is waiting for the MICSR object
cloudManager.js?4675:199 Silent Sign in with JWT
cloudManager.js?4675:199 Validating Melvor Cloud token
cloudManager.js?4675:199 Storing Melvor Cloud Token
cloudManager.js?4675:199 Initializing PlayFab login. Method: customID
cloudManager.js?4675:199 Logging in with Custom ID via PlayFab
cloudManager.js?4675:199 Login with custom ID success
cloudManager.js?4675:199 Getting account info
cloudManager.js?4675:199 Account info retrieved
cloudManager.js?4675:199 Authenticated w/ Melvor Cloud: true
cloudManager.js?4675:199 Authenticated w/ PlayFab: true
cloudManager.js?4675:199 Checking for valid full version
cloudManager.js?4675:199 Checking for valid TotH purchase
cloudManager.js?4675:199 Loading Game Data...
save.js?4675:111 Registered Demo Data.
save.js?4675:111 Registered Full Version Data.
save.js?4675:111 Registered Throne of the Herald Data.
cloudManager.js?4675:199 Initializing Mod Manager...
cloud.js?4675:147 PlayFab Data Stored successfully.
cloudManager.js?4675:199 Checking for Mod Updates...
cloudManager.js?4675:199 Loading Mods...
cloudManager.js?4675:199 Loading Local Saves...
cloudManager.js?4675:199 Loading Cloud Saves...
cloudManager.js?4675:199 Getting saves from playfab
cloudManager.js?4675:199 Saves retrieved
characterSelect.js?4675:5 Loading character selection
cloudManager.js?4675:294 Connected to PlayFab successfully
save.js?4675:39 Copied to clipboard successfully.
main.js?4675:15 Game Loaded
main.js:99 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (main.js:99:35)
    at main.js:124:30
util.js:251 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (util.js:251:35)
    at util.js:276:30
modifierNames.js:931 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (modifierNames.js:931:35)
    at modifierNames.js:956:30
AgilityCourse.js:255 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (AgilityCourse.js:255:35)
    at AgilityCourse.js:280:30
Card.js:605 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (Card.js:605:35)
    at Card.js:630:30
CombatData.js:174 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (CombatData.js:174:35)
    at CombatData.js:199:30
Consumables.js:397 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (Consumables.js:397:35)
    at Consumables.js:422:30
DataExport.js:186 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (DataExport.js:186:35)
    at DataExport.js:211:30
ExportCheat.js:192 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (ExportCheat.js:192:35)
    at ExportCheat.js:217:30
Import.js:476 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (Import.js:476:35)
    at Import.js:501:30
Plotter.js:545 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (Plotter.js:545:35)
    at Plotter.js:570:30
Loot.js:585 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (Loot.js:585:35)
    at Loot.js:610:30
Menu.js:168 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (Menu.js:168:35)
    at Menu.js:193:30
Simulator.js:1173 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (Simulator.js:1173:35)
    at Simulator.js:1198:30
SimEnemy.js:75 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (SimEnemy.js:75:35)
    at SimEnemy.js:100:30
SimManager.js:330 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (SimManager.js:330:35)
    at SimManager.js:355:30
SimPlayer.js:807 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (SimPlayer.js:807:35)
    at SimPlayer.js:832:30
TabCard.js:131 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (TabCard.js:131:35)
    at TabCard.js:156:30
App.js:3018 Uncaught ReferenceError: characterLoading is not defined
    at waitLoadOrder (App.js:3018:35)
    at App.js:3043:30
vaafb692b2aea4879b33c060e79fe94621666317369993:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
vaafb692b2aea4879b33c060e79fe94621666317369993:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
cloud.js?4675:29 Synchronising with Cloud
style.css:1          Failed to load resource: the server responded with a status of 404 ()
DevTools failed to load source map: Could not load content for https://melvoridle.com/assets/js/popper.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://melvoridle.com/assets/js/tippy-bundle.umd.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://melvoridle.com/sm/57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4675

### Are you using any mods?

No

**Comment by pelletier2017** [comment]
Nevermind someone on melvor discord said this happened for everyone and its not a bug.
