### ISSUE TITLE
Save stuck in stunned state, unable to play as a result.

### ISSUE THREAD

**Issue by MichaelFenwick** [MelvorIdle/melvoridle.github.io#2912]
### Describe the bug

I had just started thieving and got stunned, at which point the below error message appeared.
I refreshed the browser page, and reopened my save file. When the game loaded back up, I received a message saying that the save couldn't be loaded because TotH content was found but the expansion was not installed.
I refreshed my browser page again, and it showed that I wasn't logged in anymore. Upon logging in, I was able to load my save file.
Now, my save file is stuck in a state where no matter what I try to do, I get the message "You cannot do that. You are stunned!" The only actions that seem to work are changing equipment or doing things in Township and Farming. This has left the game in a completely unplayable state for me.

```An error occurred while processing ticks:
Active Action: melvorD:Thieving
Error Name: TypeError
Error Message: Cannot read properties of undefined (reading 'toFixed')
Stack Trace:
TypeError: Cannot read properties of undefined (reading 'toFixed')
    at convert (blob:https://melvoridle.com/9495e9a3-aad8-48a0-a5d7-cdcdd5fc23c9:132:37)
    at Object.getModifiers (blob:https://melvoridle.com/9495e9a3-aad8-48a0-a5d7-cdcdd5fc23c9:91:15)
    at blob:https://melvoridle.com/45a46ec8-dea1-4827-b1b9-503a38fc2991:60:58
    at Array.forEach (<anonymous>)
    at Player.refresh (blob:https://melvoridle.com/45a46ec8-dea1-4827-b1b9-503a38fc2991:58:19)
    at typeName.<computed> (https://melvoridle.com/assets/js/built/mod.js?4675:751:52)
    at Player.computeAllStats (https://melvoridle.com/assets/js/built/character.js?4675:81:49)
    at Player.computeAllStats (https://melvoridle.com/assets/js/built/player.js?4675:55:172)
    at PotionManager.computeProvidedStats (https://melvoridle.com/assets/js/built/potionManager.js?4675:28:25)
    at PotionManager.removePotion (https://melvoridle.com/assets/js/built/potionManager.js?4675:16:47)
Current Equipment:
Helmet: melvorF:Performance_Enhancing_Hat
Platebody: melvorF:Performance_Enhancing_Body
Platelegs: melvorF:Blacksmiths_Leggings
Boots: melvorF:Necromancer_Boots
Shield: melvorF:Fine_Coinpurse
Amulet: melvorF:Jeweled_Necklace
Ring: melvorD:Ancient_Ring_Of_Skills
Gloves: melvorD:Smithing_Gloves
Quiver: melvorD:Dragon_Arrows
Cape: melvorD:Firemaking_Skillcape
Summon2: melvorF:Summoning_Familiar_Pig
Consumable: melvorF:Fishing_Hook

Action Information:
getErrorLog(){return `Is Active: ${this.isActive}\n`;}
  Selected Area: melvorF:ROYAL_CASTLE
  Selected NPC: melvorF:PRINCESS
  Stun State: 1
Modding Enabled. Loaded mods:
Dev
SEMI Core
SEMI Drop Chances
SEMI Auto Master
SEMI Auto Farming
SEMI Auto Loot
SEMI Save on Close
SEMI Auto Open
Right Click Equip Menu
Mastery Virtual Levels
SEMI Auto Sell
Township Breakdown
QuickShards
SEMI Auto Bury
SEMI XP Per Hour
Quick Item/Bank Wiki
SEMI Auto Eat
SEMI Auto Run
Undo Sell
Real Quick Equip
Township Grid Display
Shop Item Owned Indicator
Show Skill Modifiers
SEMI Auto Slayer
Melvor Modifiers Exposed
ETA
Item Uses```

### Reproduction Steps

_No response_

### Expected behaviour

_No response_

### Save Link

https://melvoridle.com/save/RWPb15QM

### Screenshots

_No response_

### Console output

```style.css:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: the server responded with a status of 404 ()
vaafb692b2aea4879b33c060e79fe94621666317369993:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
vaafb692b2aea4879b33c060e79fe94621666317369993:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
vaafb692b2aea4879b33c060e79fe94621666317369993:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
​ Silent Sign in with JWT
​ Validating Melvor Cloud token
​ Storing Melvor Cloud Token
​ Initializing PlayFab login. Method: customID
​ Logging in with Custom ID via PlayFab
​ Login with custom ID success
​ Getting account info
​ Account info retrieved
​ Authenticated w/ Melvor Cloud: true
​ Authenticated w/ PlayFab: true
​ Checking for valid full version
​ Checking for valid TotH purchase
​ Loading Game Data...
​ Registered Demo Data.
​ Registered Full Version Data.
​ Registered Throne of the Herald Data.
​ Initializing Mod Manager...
​ PlayFab Data Stored successfully.
​ Checking for Mod Updates...
​ Loading Mods...
​ Loading Mods (1/26): SEMI Core (v1.7.2)
​ Loading Mods (2/26): SEMI Drop Chances (v1.4.0)
​ Loading Mods (3/26): SEMI Auto Master (v1.7.0)
​ Loading Mods (4/26): SEMI Auto Farming (v0.2.3)
​ Loading Mods (5/26): SEMI Auto Loot (v1.3.0)
​ Loading Mods (6/26): SEMI Save on Close (v1.1.0)
​ Loading Mods (7/26): SEMI Auto Open (v1.3.0)
​ Loading Mods (8/26): Right Click Equip Menu (v2.4)
​ Loading Mods (9/26): Mastery Virtual Levels (v0.0.9)
​ Loading Mods (10/26): SEMI Auto Sell (v1.0.1)
​ Loading Mods (11/26): Township Breakdown (v0.1.1)
​ Loading Mods (12/26): QuickShards (v1.0.0)
​ Loading Mods (13/26): SEMI Auto Bury (v0.0.4)
​ Loading Mods (14/26): SEMI XP Per Hour (v1.4.1)
​ Loading Mods (15/26): Quick Item/Bank Wiki (v1.2.1.0032)
​ Loading Mods (16/26): SEMI Auto Eat (v1.4.0)
​ Loading Mods (17/26): SEMI Auto Run (v1.3.0)
​ Loading Mods (18/26): Undo Sell (v1.0.7)
​ Loading Mods (19/26): Real Quick Equip (v1.7.9)
​ Loading Mods (20/26): Township Grid Display (v1.1.4)
​ Loading Mods (21/26): Shop Item Owned Indicator (v1.1.2)
​ Loading Mods (22/26): Show Skill Modifiers (v1.4.3)
​ Loading Mods (23/26): SEMI Auto Slayer (v1.1.0)
​ Loading Mods (24/26): Melvor Modifiers Exposed (v1.1.31c)
​ Loading Mods (25/26): ETA (v1.0.0-46)
​ Loading Mods (26/26): Item Uses (v0.0.5)
​ Loading Local Saves...
​ Loading Cloud Saves...
​ Getting saves from playfab
​ Saves retrieved
​ Loading character selection
​ Connected to PlayFab successfully
​ Game Loaded
​ 
        
       [SEMI Auto Open] Possible mod conflict - Bank.addItem has already been patched by the following mods: "Shop Item Owned Indicator"
patch @ mod.js:734
​ 
        
       [SEMI Auto Sell] Possible mod conflict - Bank.addItem has already been patched by the following mods: "Shop Item Owned Indicator", "SEMI Auto Open"
patch @ mod.js:734
​ 
        
       [SEMI Auto Bury] Possible mod conflict - Bank.addItem has already been patched by the following mods: "Shop Item Owned Indicator", "SEMI Auto Open", "SEMI Auto Sell"
patch @ mod.js:734
16153a9e-52e9-4689-b782-e4b01e12728a:223 Melvor Equipment Menu Loaded
​ 
        
       [Quick Item/Bank Wiki] Possible mod conflict - BankSelectedItemMenu.setItem has already been patched by the following mods: "Item Uses"
patch @ mod.js:734
​ 
        
       [Township Grid Display] Possible mod conflict - Township.catchupTicks has already been patched by the following mods: "Township Breakdown"
patch @ mod.js:734
​ 
        
       [Township Grid Display] Possible mod conflict - TownshipUI.getPageButton has already been patched by the following mods: "Township Breakdown"
patch @ mod.js:734
​ 
        
       [Township Grid Display] Possible mod conflict - TownshipUI.showPage has already been patched by the following mods: "Township Breakdown"
patch @ mod.js:734
​ 
        
       [Melvor Modifiers Exposed] TypeError: Cannot read properties of undefined (reading 'toFixed')
    at convert (7373993a-86c5-431c-95e2-cf7c3bdc300d:132:37)
    at Object.getModifiers (7373993a-86c5-431c-95e2-cf7c3bdc300d:91:15)
    at 1c1ca550-8973-4fc5-b8cc-cdd039fd5d00:80:53
    at Array.forEach (<anonymous>)
    at 1c1ca550-8973-4fc5-b8cc-cdd039fd5d00:79:19
    at mod.js:767:46
    at Generator.next (<anonymous>)
    at fulfilled (language.js:2:98)
(anonymous) @ mod.js:768
c0b71ebc-a128-478a-814c-fb99c49a6f4a:559 ETA : Loading...
c0b71ebc-a128-478a-814c-fb99c49a6f4a:559 ETA : added settings menu!
c0b71ebc-a128-478a-814c-fb99c49a6f4a:559 ETA : Loaded!
vaafb692b2aea4879b33c060e79fe94621666317369993:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
vaafb692b2aea4879b33c060e79fe94621666317369993:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
​ Synchronising with Cloud
22Unchecked runtime.lastError: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
style.css:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: the server responded with a status of 404 ()
DevTools failed to load source map: Could not load content for https://melvoridle.com/sm/57190bfad76800342541d15d95d26784376ee1fcc2f3eae66a629600709e4186.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE```

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [X] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.1.0

### Game Subversion

?4675

### Are you using any mods?

Yes

**Comment by VixaZ** [comment]
Same issue here. Running Firefox, disabling mods didn't help.

**Comment by MichaelFenwick** [comment]
@VixaZ  I did eventually manage to find a way to "fix" this, at least to the extent that it allows me to play again.

To "unlock" yourself, type `game.thieving.stunState = 0` into the console.
If you want to compensate for time lost while stuck, you can do so by running `game.runTicks(x)` in the console where x is 100 times the number of seconds you want to make up.

**Comment by MichaelFenwick** [comment]
Despite the workaround detailed above, I'm leaving this open as there is still an underlying problem that allowed saves to get stuck in this state in the first place. Ideally, the cause of this can be resolved.

I'd also recommend adding something to the game that doesn't just keep track of your stunned state (true or false) but rather stores the timestamp when you were stunned (or undefined/null if not stunned). Anything checking to see if you're stunned could then check to see if that variable is set to a time within the last 5 seconds, and only consider you stunned if so. If the variable is set to undefined/null, OR the timestamp is older than 5 seconds, then it would consider you not stunned. If the stunned state gets out of sync of other data or otherwise stuck, this would prevent it from locking the player completely.

**Comment by MelvorIdle** [comment]
The stack trace you provided shows that this error is due to one of the Mods you have installed.

I suggest going through each mod and disabling/enabling until the culprit is found, and notifying the Mod developer.
