### ISSUE TITLE
[Bug]: cartography will not load past 4%

### ISSUE THREAD

**Issue by Jwcom93** [MelvorIdle/melvoridle.github.io#4218]
### Describe the bug

When I open the cartography skill, the map does not load past 4%

### Reproduction Steps

1 click on cartography still
2 wait for it to load past 4%
3 will not load

### Expected behaviour

Should load past 4%
Should be able to use skill?

### Which platforms are you experiencing this bug on?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] Steam
- [ ] Epic Games
- [X] Mobile App (iOS)
- [ ] Mobile App (Android)
- [ ] Mobile App (Android Beta)
- [ ] Other (Please Specify)

### Which expansions are purchased and active at the time of the bug?

- [X] Throne of the Herald
- [X] Atlas of Discovery

### Which version of the game are you experiencing this bug on?

v1.2.2

### Game Subversion

?8605

### Are you using any mods?

No

**Comment by AndiSwiss** [comment]
Same here. The bug is still present: stops loading at 4% (no matter what settings I choose for cartography).

IMPORTANT: The bug didn‘t occur when I had fast WiFi. But now, I‘m in an area with slower WiFi for a couple of days, and it always gets stuck (on iPhone and on iPad). Slow as in: I still can do video calls, but with medium quality only).

No mods, all 3 extensions are active.

Happens on my regular 47 days save with 1,700 Skill Levels (standard mode, including tutorial island completion). But also on a fresh new game, standard mode, skipping tutorial island

**Comment by higef** [comment]
Happened to me on Steam-OSX client, Chrome-browser and Android. Console trace:
```
cartographyMenu.js?12094:231 Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'texture')
    at HTMLElement.<anonymous> (cartographyMenu.js?12094:231:36)
    at Generator.next (<anonymous>)
    at fulfilled (nativeManager.js?12094:5:58)
(anonymous)	@	cartographyMenu.js?12094:231
fulfilled	@	nativeManager.js?12094:5
Promise.then		
step	@	nativeManager.js?12094:7
fulfilled	@	nativeManager.js?12094:5
Promise.then		
step	@	nativeManager.js?12094:7
(anonymous)	@	nativeManager.js?12094:8
__awaiter	@	nativeManager.js?12094:4
init	@	cartographyMenu.js?12094:222
(anonymous)	@	cartographyMenu.js?12094:389
(anonymous)	@	nativeManager.js?12094:8
__awaiter	@	nativeManager.js?12094:4
onShow	@	cartographyMenu.js?12094:387
(anonymous)	@	cartography.js?12094:2446
(anonymous)	@	nativeManager.js?12094:8
__awaiter	@	nativeManager.js?12094:4
onPageVisible	@	cartography.js?12094:2444
changePage	@	uiCallbacks.js?12094:763
(anonymous)	@	main.js?12094:130
(anonymous)	@	nativeManager.js?12094:8
__awaiter	@	nativeManager.js?12094:4
updateWindow	@	main.js?12094:47
(anonymous)	@	main.js?12094:567
(anonymous)	@	nativeManager.js?12094:8
__awaiter	@	nativeManager.js?12094:4
onSaveDataLoad	@	main.js?12094:566
(anonymous)	@	save.js?12094:825
fulfilled	@	nativeManager.js?12094:5
```
and 
```index.js:77 Uncaught Error: Unable to auto-detect a suitable renderer.
    at wa (index.js:77:1)
    at new xn (earcut.js:116:1)
    at new WorldMapDisplayElement (cartographyMenu.js?12094:115:20)
    at Cartography.onLoad (cartography.js?12094:2386:31)
    at game.js?12094:1642:19
    at Map.forEach (<anonymous>)
    at NamespaceRegistry.forEach (namespaceRegistry.js?12094:205:32)
    at Game.onLoad (game.js?12094:1641:21)
    at main.js?12094:99:18
    at Generator.next (<anonymous>)
```

managed to make it pass through the Cartography loading by using Safari browser, changed the active skill and loaded it through my default Steam client

UPD: I assume that happened after the whole Map were surveyed and Mastery level 5 were unlocked for all the hexes
